// Post-build quality gate. Fails (exit 1) on broken links, bad metadata, heading problems and leftover artifacts.
// Usage: node scripts/check-site.mjs   (run after `astro build`)
import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { parse } from 'node-html-parser';

const DIST = join(process.cwd(), 'dist');
const SITE = process.env.PUBLIC_SITE_URL || 'https://distritogamer.com';
if (!existsSync(DIST)) { console.error('dist/ not found. Run `astro build` first.'); process.exit(1); }

const errors = [], warnings = [];
const err = (p, m) => errors.push(`${p}: ${m}`);
const warn = (p, m) => warnings.push(`${p}: ${m}`);

function walk(dir, out = []) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    statSync(p).isDirectory() ? walk(p, out) : out.push(p);
  }
  return out;
}
const files = walk(DIST);
const htmlFiles = files.filter((f) => f.endsWith('.html'));
const pageUrl = (f) => '/' + relative(DIST, f).replace(/index\.html$/, '').replace(/\.html$/, '/').replace(/\\/g, '/');

const docs = new Map(), fileOf = new Map();
for (const f of htmlFiles) { docs.set(pageUrl(f), parse(readFileSync(f, 'utf8'))); fileOf.set(pageUrl(f), f); }

const exists = (urlPath) => {
  const clean = decodeURI(urlPath.split('#')[0].split('?')[0]);
  if (docs.has(clean) || docs.has(clean.endsWith('/') ? clean : clean + '/')) return true;
  const fp = join(DIST, clean);
  return existsSync(fp) && statSync(fp).isFile();
};

const FORBIDDEN = [/lorem ipsum/i, /\bTODO\b/, /\bFIXME\b/, /AFFILIATE_LINK_PLACEHOLDER/, /\[object Object\]/, /\bundefined\b/, /console\.log/, /\bas an AI\b/i, /\bChatGPT\b/i, /generated by (an )?AI/i];
const titles = new Map(), descs = new Map();
let homeWords = 0;
const articleWords = [];

for (const [url, root] of docs) {
  const is404 = url === '/404/';
  const html = readFileSync(fileOf.get(url), 'utf8');

  // metadata
  const title = root.querySelector('title')?.text?.trim() || '';
  const desc = root.querySelector('meta[name="description"]')?.getAttribute('content') || '';
  if (!title) err(url, 'missing <title>');
  else {
    if (title.length > 60) warn(url, `title is ${title.length} chars (aim <= 60): "${title}"`);
    if (title.length < 25) warn(url, `title is short (${title.length})`);
    (titles.get(title) ?? titles.set(title, []).get(title)).push(url);
  }
  if (!desc) err(url, 'missing meta description');
  else {
    if (desc.length > 160) err(url, `meta description ${desc.length} chars (max 160)`);
    if (desc.length < 70) warn(url, `meta description short (${desc.length})`);
    (descs.get(desc) ?? descs.set(desc, []).get(desc)).push(url);
  }
  const canonical = root.querySelector('link[rel="canonical"]')?.getAttribute('href');
  if (!canonical) err(url, 'missing canonical');
  else if (canonical !== SITE + url) err(url, `canonical ${canonical} != ${SITE + url}`);
  for (const k of ['meta[property="og:image"]', 'meta[name="twitter:image"]']) {
    const v = root.querySelector(k)?.getAttribute('content');
    if (v && v.startsWith(SITE) && !exists(v.slice(SITE.length))) err(url, `social image missing in dist: ${v}`);
  }
  for (const sel of ['meta[property="og:title"]', 'meta[property="og:description"]', 'meta[property="og:image"]', 'meta[property="og:url"]', 'meta[name="twitter:card"]', 'meta[name="viewport"]'])
    if (!root.querySelector(sel)) err(url, `missing ${sel}`);
  if (root.querySelector('html')?.getAttribute('lang') !== 'en') err(url, 'html lang should be "en"');

  // structured data must parse
  for (const s of root.querySelectorAll('script[type="application/ld+json"]')) {
    try { JSON.parse(s.text); } catch (e) { err(url, 'invalid JSON-LD: ' + e.message); }
  }

  // headings
  const heads = root.querySelectorAll('h1,h2,h3,h4,h5,h6').map((h) => ({ l: +h.tagName[1], t: h.text.trim() }));
  const h1s = heads.filter((h) => h.l === 1);
  if (h1s.length !== 1) err(url, `expected exactly one h1, found ${h1s.length}`);
  let prev = 0;
  for (const h of heads) {
    if (prev && h.l > prev + 1) err(url, `heading level jumps h${prev} -> h${h.l} at "${h.t.slice(0, 50)}"`);
    if (!prev && h.l !== 1) err(url, 'first heading is not h1');
    prev = h.l;
  }

  // accessibility basics
  for (const img of root.querySelectorAll('img')) {
    if (img.getAttribute('alt') === undefined) err(url, `img without alt: ${img.getAttribute('src')}`);
    if (!img.getAttribute('width') || !img.getAttribute('height')) warn(url, `img missing width/height (CLS): ${img.getAttribute('src')}`);
  }
  for (const n of root.querySelectorAll('nav')) if (!n.getAttribute('aria-label') && !n.getAttribute('aria-labelledby')) err(url, 'nav without aria-label');
  for (const a of root.querySelectorAll('aside')) {
    if (a.getAttribute('role') === 'complementary') err(url, 'aside must not set role="complementary"');
    if (!a.getAttribute('aria-label') && !a.getAttribute('aria-labelledby')) err(url, 'aside without aria-label');
  }
  for (const a of root.querySelectorAll('a')) {
    if (!a.text.trim() && !a.getAttribute('aria-label') && !a.querySelector('.sr')) err(url, `link without accessible name: ${a.getAttribute('href')}`);
    if (/^(click here|here|read more)$/i.test(a.text.trim())) warn(url, `generic link text "${a.text.trim()}"`);
  }
  for (const b of root.querySelectorAll('button')) if (!b.text.trim() && !b.getAttribute('aria-label')) err(url, 'button without accessible name');
  for (const i of root.querySelectorAll('input,textarea,select')) {
    const id = i.getAttribute('id');
    if (i.getAttribute('type') === 'hidden') continue;
    if (!id || !root.querySelector(`label[for="${id}"]`)) err(url, `form control without label: ${id}`);
  }
  if (!root.querySelector('main#main')) err(url, 'missing <main id="main">');

  // links
  for (const a of root.querySelectorAll('a[href]')) {
    const href = a.getAttribute('href');
    if (/^(mailto:|tel:|javascript:)/.test(href)) continue;
    if (/^https?:\/\//.test(href)) {
      if (href.startsWith(SITE)) err(url, `absolute self link (use relative): ${href}`);
      else if (a.getAttribute('target') === '_blank' && !/noopener/.test(a.getAttribute('rel') || '')) err(url, `external _blank link missing rel=noopener: ${href}`);
      continue;
    }
    if (href.startsWith('#')) { if (href.length > 1 && !root.querySelector(`[id="${href.slice(1)}"]`)) err(url, `broken anchor ${href}`); continue; }
    if (!exists(href)) { err(url, `broken internal link ${href}`); continue; }
    const [pth, hash] = href.split('#');
    if (hash) {
      const target = docs.get(pth.endsWith('/') ? pth : pth + '/') || docs.get(pth);
      if (target && !target.querySelector(`[id="${hash}"]`)) err(url, `broken anchor ${href}`);
    }
  }
  for (const el of root.querySelectorAll('[src],link[href]')) {
    const v = el.getAttribute('src') || el.getAttribute('href');
    if (!v || /^(https?:|data:|#|mailto:)/.test(v)) continue;
    if (el.tagName === 'A') continue;
    if (!exists(v)) err(url, `missing asset ${v}`);
  }
  for (const s of root.querySelectorAll('img[srcset],source[srcset]')) {
    for (const part of s.getAttribute('srcset').split(',')) {
      const u = part.trim().split(/\s+/)[0];
      if (u && !/^https?:/.test(u) && !exists(u)) err(url, `missing srcset asset ${u}`);
    }
  }

  // leftovers
  const bodyText = root.querySelector('body')?.text ?? '';
  for (const re of FORBIDDEN) if (re.test(bodyText) || re.test(html.replace(/<script[\s\S]*?<\/script>/g, ''))) err(url, `forbidden artifact: ${re}`);

  // word counts
  const main = root.querySelector('main');
  const words = (main?.text.match(/[\p{L}\p{N}'’-]+/gu) || []).length;
  if (url === '/') { homeWords = words; if (words < 8000) err(url, `homepage has ${words} words (target 8000+)`); }
  const isArticle = root.querySelector('meta[property="og:type"]')?.getAttribute('content') === 'article';
  if (isArticle) {
    const w = (root.querySelector('.prose')?.text.match(/[\p{L}\p{N}'’-]+/gu) || []).length;
    articleWords.push([url, w]);
    if (w < 1450) warn(url, `article body ${w} words (target 1500+)`);
    for (const k of ['.quick', '.toc', '.byline time', '.author-box']) if (!root.querySelector(k)) err(url, `article missing ${k}`);
    if (!/"@type":"Article"/.test(html)) err(url, 'article missing Article JSON-LD');
  }
}

for (const [t, urls] of titles) if (urls.length > 1) err(urls.join(', '), `duplicate title "${t}"`);
for (const [d, urls] of descs) if (urls.length > 1) err(urls.join(', '), 'duplicate meta description');

// sitemap / robots
const sm = join(DIST, 'sitemap-index.xml');
if (!existsSync(sm)) err('sitemap', 'sitemap-index.xml missing');
else {
  const idx = readFileSync(sm, 'utf8');
  const child = (idx.match(/<loc>([^<]+)<\/loc>/g) || []).map((s) => s.replace(/<\/?loc>/g, ''));
  const urls = new Set();
  for (const c of child) {
    const fp = join(DIST, c.replace(SITE, ''));
    if (!existsSync(fp)) { err('sitemap', `child sitemap missing ${c}`); continue; }
    for (const m of readFileSync(fp, 'utf8').matchAll(/<loc>([^<]+)<\/loc>/g)) urls.add(m[1]);
  }
  for (const [url, root] of docs) {
    if (url === '/404/') continue;
    const noindex = /noindex/.test(root.querySelector('meta[name="robots"]')?.getAttribute('content') || '');
    const inMap = urls.has(SITE + url);
    if (!noindex && !inMap && url !== '/search/') err('sitemap', `indexable page missing from sitemap: ${url}`);
    if (noindex && inMap) err('sitemap', `noindex page present in sitemap: ${url}`);
  }
  console.log(`sitemap: ${urls.size} URLs`);
}
const robotsPath = join(DIST, 'robots.txt');
if (!existsSync(robotsPath)) err('robots', 'robots.txt missing');
else {
  const r = readFileSync(robotsPath, 'utf8');
  if (!/Sitemap:\s*https?:\/\//.test(r)) err('robots', 'no Sitemap directive');
  if (/Disallow:\s*\/(_astro|fonts)/.test(r)) err('robots', 'blocks render-critical assets');
}
for (const need of ['_headers', 'favicon.svg', 'global.css']) if (!existsSync(join(DIST, need))) err('assets', `${need} missing in dist`);

// JS/CSS budget
const jsFiles = files.filter((f) => f.endsWith('.js'));
const jsKb = jsFiles.reduce((n, f) => n + statSync(f).size, 0) / 1024;
console.log(`javascript shipped: ${jsKb.toFixed(1)} KB across ${jsFiles.length} file(s)`);
if (jsKb > 40) warn('perf', `JS payload ${jsKb.toFixed(1)} KB exceeds 40 KB budget`);
const fonts = files.filter((f) => f.endsWith('.woff2'));
console.log(`fonts: ${fonts.length} self-hosted woff2 file(s)`);
console.log(`pages: ${docs.size}, homepage words: ${homeWords}`);
const aw = articleWords.map((x) => x[1]);
if (aw.length) console.log(`articles: ${aw.length}, body words min/avg/max: ${Math.min(...aw)}/${Math.round(aw.reduce((a, b) => a + b, 0) / aw.length)}/${Math.max(...aw)}`);

if (warnings.length) console.log(`\n${warnings.length} warning(s):\n` + warnings.map((w) => '  - ' + w).join('\n'));
if (errors.length) { console.error(`\n${errors.length} ERROR(S):\n` + errors.map((e) => '  x ' + e).join('\n')); process.exit(1); }
console.log('\nAll site checks passed.');
