#!/usr/bin/env node
// Generates the reference-data and editorial-content migrations from /content.
//   node scripts/build-seed.mjs
// Output: migrations/0002_reference_data.sql, migrations/0003_editorial_content.sql
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { cities } from '../content/cities.mjs';
import { makes, categories } from '../content/makes.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);

const q = (v) => (v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const slugify = (s) => s.toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

// ── Reference data ──
const ref = ['-- GENERATED by scripts/build-seed.mjs — edit /content and re-run instead of editing this file.', ''];

ref.push('-- Alabama cities with unique landing-page content');
for (const c of cities) {
  ref.push(
    `INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES (${[
      c.slug, c.name, c.county, c.lat, c.lng, c.featured, c.sort, c.intro, c.body, JSON.stringify(c.faq),
    ].map(q).join(', ')});`,
  );
}

ref.push('', '-- Makes and models');
for (const mk of makes) {
  const slug = slugify(mk.name);
  ref.push(`INSERT INTO makes (slug, name, is_popular, intro) VALUES (${q(slug)}, ${q(mk.name)}, ${mk.popular ? 1 : 0}, ${q(mk.intro ?? null)});`);
  for (const md of mk.models) {
    ref.push(
      `INSERT INTO models (make_id, slug, name, body_type) SELECT id, ${q(slugify(md.name))}, ${q(md.name)}, ${q(md.body)} FROM makes WHERE slug = ${q(slug)};`,
    );
  }
}

ref.push('', '-- Blog categories');
categories.forEach((c, i) => ref.push(`INSERT INTO categories (slug, name, description, sort_order) VALUES (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${i + 1});`));

// Alabama ZIP codes (lat/lng) from the `zipcodes` package (BSD-licensed, derived from public US data).
const zipcodes = require('zipcodes');
const zips = Object.values(zipcodes.codes).filter((z) => z.state === 'AL' && /^\d{5}$/.test(z.zip) && z.latitude && z.longitude);
zips.sort((a, b) => a.zip.localeCompare(b.zip));
ref.push('', `-- ${zips.length} Alabama ZIP codes for radius search`);
for (let i = 0; i < zips.length; i += 100) {
  const chunk = zips.slice(i, i + 100).map((z) => `(${q(z.zip)}, ${q(z.city)}, 'AL', ${Number(z.latitude)}, ${Number(z.longitude)})`);
  ref.push(`INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ${chunk.join(',\n  ')};`);
}

ref.push('', '-- Editorial byline account (cannot sign in: password hash is not a valid PBKDF2 string)');
ref.push(
  `INSERT INTO users (email, password_hash, name, role, status, author_slug, author_title, author_bio) VALUES ('editorial@bamamotors.com', '!disabled', 'BamaMotors Editorial Team', 'admin', 'active', 'bamamotors-editorial-team', 'Editorial Team', ${q(
    'The BamaMotors editorial team writes and maintains our car buying, financing and ownership guides for Alabama drivers. We research title, registration, tax and consumer-protection topics from official sources such as the Alabama Department of Revenue, the FTC and NHTSA, cite those sources in our articles, and review guides regularly so they stay current. Dealers cannot pay for editorial coverage.',
  )});`,
);

writeFileSync(join(root, 'migrations/0002_reference_data.sql'), `${ref.join('\n')}\n`);

// ── Editorial content ──
function parsePost(file) {
  const raw = readFileSync(join(root, 'content/posts', file), 'utf8');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`Missing frontmatter in ${file}`);
  const meta = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i < 0) continue;
    let v = line.slice(i + 1).trim();
    if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
    meta[line.slice(0, i).trim()] = v;
  }
  for (const k of ['title', 'category', 'excerpt', 'meta_description']) if (!meta[k]) throw new Error(`${file}: missing ${k}`);
  if (meta.meta_description.length > 160) throw new Error(`${file}: meta_description is ${meta.meta_description.length} chars (max 160)`);
  const faq = meta.faq ? JSON.parse(meta.faq) : [];
  const howto = meta.howto ? JSON.parse(meta.howto) : null;
  return { slug: file.replace(/\.md$/, ''), ...meta, faq, howto, body: m[2].trim() };
}

const allPosts = readdirSync(join(root, 'content/posts')).filter((f) => f.endsWith('.md')).sort().map(parsePost);
// Each batch is its own migration so new guides reach existing databases (migrations never re-run).
const batches = { '0003_editorial_content.sql': allPosts.filter((p) => (p.batch ?? '1') === '1'), '0004_more_guides.sql': allPosts.filter((p) => p.batch === '2') };
for (const [file, posts] of Object.entries(batches)) {
const content = ['-- GENERATED by scripts/build-seed.mjs — original editorial guides. Admins can edit these in /admin/posts.', ''];
for (const p of posts) {
  content.push(
    `INSERT INTO blog_posts (slug, title, excerpt, body, category_id, author_id, status, meta_title, meta_description, keywords, faq_json, howto_json, published_at, updated_at)
SELECT ${q(p.slug)}, ${q(p.title)}, ${q(p.excerpt)}, ${q(p.body)}, (SELECT id FROM categories WHERE slug = ${q(p.category)}),
       (SELECT id FROM users WHERE author_slug = 'bamamotors-editorial-team'), 'published', NULL, ${q(p.meta_description)}, ${q(p.keywords ?? null)},
       ${q(p.faq.length ? JSON.stringify(p.faq) : null)}, ${q(p.howto ? JSON.stringify(p.howto) : null)},
       strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now');`,
  );
}
writeFileSync(join(root, 'migrations', file), `${content.join('\n')}\n`);
}
console.log(`cities=${cities.length} makes=${makes.length} zips=${zips.length} posts=${allPosts.length}`);
