import manifest from '../data/images.json';

/**
 * Licensed stock photos (Pexels License — free to use, no attribution required; we credit anyway).
 * Generated by scripts/fetch-pexels.mjs into public/images and src/data/images.json.
 * Every helper returns null when an image hasn't been fetched yet, so pages degrade gracefully.
 */
export interface SiteImage {
  src: string; // largest WebP
  srcset: string;
  width: number;
  height: number;
  alt: string;
  photographer: string;
  photographerUrl: string;
  pexelsUrl: string;
}

const images = manifest as Record<string, SiteImage>;

export const image = (key: string): SiteImage | null => images[key] ?? null;
export const cityImage = (slug: string) => image(`city-${slug}`) ?? image('city-default');
export const postImage = (slug: string) => image(`post-${slug}`) ?? image('post-default');
export const bodyImage = (slug: string) => image(`body-${slug}`);
export const allImages = () => images;
