-- GENERATED by scripts/build-seed.mjs — edit /content and re-run instead of editing this file.

-- Alabama cities with unique landing-page content
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('birmingham-al', 'Birmingham', 'Jefferson County', 33.5186, -86.8104, 1, 1, 'Shop used cars for sale in Birmingham, AL from local dealerships across the Magic City and the wider metro: Hoover, Vestavia Hills, Homewood, Trussville and Bessemer. Compare prices, mileage and dealer details, then contact the dealer directly.', '## Buying a used car in Birmingham

Birmingham is Alabama''s largest metro area, and that scale works in a shopper''s favor: more dealerships means more choice and more room to compare prices on the same model. Commuters who split time between downtown, UAB and the southern suburbs put real miles on I-65, I-20/59 and I-459, so it pays to look closely at how a vehicle was driven, not just how old it is.

### What to check on a Birmingham used car

- **Highway vs. city miles.** A higher-mileage car used for interstate commuting can be in better mechanical shape than a low-mileage car that lived in stop-and-go traffic. Ask the dealer for service records.
- **Hills and brakes.** Neighborhoods on Red Mountain and Shades Mountain are hard on brakes and transmissions. Listen for grinding and feel for shuddering on a test drive.
- **Summer heat.** Test the A/C at full blast for several minutes. A weak system is a common and expensive surprise in central Alabama summers.

### Where Birmingham drivers shop

Dealerships cluster along US-280, US-31 through Hoover and Homewood, and the Bessemer and Fultondale corridors. Use the radius filter to include the whole metro, or narrow to a specific ZIP code if you want to stay close to home.

### Paperwork in Jefferson County

After purchase, the vehicle is titled and registered through the county. Jefferson County has courthouse locations in both Birmingham and Bessemer, so check which office serves your address before you go. See our [guide to buying a used car in Alabama](/blog/how-to-buy-a-used-car-in-alabama) for the full checklist.', '[{"q":"Which areas does the Birmingham used car search include?","a":"By default we show vehicles from dealers within about 30 miles of downtown Birmingham, which covers Hoover, Vestavia Hills, Homewood, Trussville, Bessemer and Gardendale. Change the radius or enter a ZIP code to widen or narrow the search."},{"q":"Can I find used trucks and SUVs in Birmingham on BamaMotors?","a":"Yes. Use the body type filter or visit the Birmingham trucks and Birmingham SUVs pages, which show only pickups or SUVs from dealers in the Birmingham area."},{"q":"Do I contact the dealer or BamaMotors about a car?","a":"You contact the dealership directly. Every listing has Contact Dealer, Request Price and Schedule Test Drive buttons that send your request straight to the dealer that owns the vehicle."},{"q":"Where do I register a used car I bought in Birmingham?","a":"Vehicles are titled and registered through the county where you live. Jefferson County residents can use the county license offices; confirm current locations, hours and fees on the county website before visiting."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('huntsville-al', 'Huntsville', 'Madison County', 34.7304, -86.5861, 1, 2, 'Find used cars for sale in Huntsville, AL from dealers across the Rocket City, Madison, Athens, Decatur and the Tennessee Valley. Filter by make, price and mileage and send your questions straight to local dealerships.', '## Used cars in Huntsville and the Tennessee Valley

Huntsville is one of the fastest-growing cities in Alabama, anchored by Redstone Arsenal, NASA''s Marshall Space Flight Center and Cummings Research Park. A growing population means steady demand for dependable commuter cars, family SUVs and pickups, and a busy used car market along Memorial Parkway, University Drive and the I-565 corridor.

### Tips for Huntsville shoppers

- **Commute first.** Many Huntsville drivers commute to Redstone Arsenal or Research Park daily. Fuel economy and comfort matter more than you think on a year of I-565 traffic. Compare MPG in the listing specs.
- **Look beyond city limits.** Madison, Athens and Decatur dealers are a short drive away. A 50-mile radius search around a Huntsville ZIP code often surfaces more choices at competitive prices.
- **Newer vehicles are common.** With vehicles now being built nearby, the market includes plenty of late-model inventory. Compare certified pre-owned options alongside standard used cars.

### Weather considerations

North Alabama sees occasional ice and snow in winter and heavy spring storms. All-wheel drive isn''t required for most drivers, but good tires matter. Check tread depth and tire age (the four-digit DOT date code) on any car you consider.

Ready to narrow it down? Start with [used SUVs](/used-cars/huntsville-al/suvs) or [used trucks](/used-cars/huntsville-al/trucks) in Huntsville.', '[{"q":"Does the Huntsville search include Madison and Athens?","a":"Yes. The Huntsville page shows vehicles from dealers within roughly 30 miles of Huntsville, which includes Madison and nearby areas. Increase the radius to include Decatur, Athens and beyond."},{"q":"Are there certified pre-owned cars for sale in Huntsville?","a":"Many dealers list certified pre-owned vehicles. Use the Condition filter and choose Certified Pre-Owned to see only those listings."},{"q":"How do I schedule a test drive with a Huntsville dealer?","a":"Open any vehicle listing and choose Schedule Test Drive. Pick a preferred date and the dealer will confirm the time with you by phone or email."},{"q":"What should I check on a used car in North Alabama?","a":"Check tire tread and age, look for storm or hail damage, test the heat and A/C, and ask for service records. A pre-purchase inspection by an independent mechanic is always a good idea."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('mobile-al', 'Mobile', 'Mobile County', 30.6954, -88.0399, 1, 3, 'Browse used cars for sale in Mobile, AL from dealerships in Mobile, Daphne, Spanish Fort, Saraland and across the Gulf Coast. Compare prices and mileage, and contact local dealers directly.', '## Buying a used car on the Gulf Coast

Mobile is Alabama''s port city, and life on Mobile Bay comes with a few things inland buyers don''t have to think about as much: salt air, humidity and hurricane season. That doesn''t make Gulf Coast cars a bad buy. It just means an informed inspection is worth the extra ten minutes.

### Gulf Coast inspection checklist

- **Rust and corrosion.** Look underneath at the frame, brake lines, exhaust and suspension mounts. Surface rust is normal; flaking or perforated metal is not.
- **Flood damage.** After major storms, flood-damaged vehicles can reach the market. Warning signs include a musty smell, damp or new carpet in an older car, silt under the seats or in the spare-tire well, and fogged headlights or gauges. Ask whether the title carries a flood or salvage brand.
- **A/C and electrical.** Humidity is hard on electronics. Test every window, lock, screen and the air conditioning.

### Shopping the Mobile area

Dealers line Airport Boulevard, the I-65 corridor and the Eastern Shore across the Bayway in Baldwin County. A 30–50 mile search around Mobile covers most of the local market.

For a deeper walk-through, read [how to spot flood damage](/blog/how-to-inspect-a-used-car-alabama) in our used car inspection guide.', '[{"q":"How can I tell if a used car in Mobile has flood damage?","a":"Check for musty odors, water lines, silt under carpets or in the trunk, corrosion on seat rails and wiring, and fogged lights. Always review the title for a flood or salvage brand and consider an independent inspection."},{"q":"Does the Mobile search include Baldwin County dealers?","a":"Dealers on the Eastern Shore, such as in Daphne and Spanish Fort, are within the default radius of Mobile. Increase the radius to reach more of Baldwin County."},{"q":"Is rust a problem on Gulf Coast cars?","a":"Salt air can speed up corrosion. Inspect the undercarriage, brake lines and exhaust. Light surface rust is common; structural rust is a reason to walk away."},{"q":"Can I get financing for a used car in Mobile?","a":"Yes. Use the Financing button on any listing to send a financing inquiry to the dealer, or visit our financing page to learn how auto loans work in Alabama."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('montgomery-al', 'Montgomery', 'Montgomery County', 32.3668, -86.3, 1, 4, 'Search used cars for sale in Montgomery, AL from dealerships in the capital city, Prattville, Millbrook and Wetumpka. Compare local prices and contact dealers directly on BamaMotors.', '## Used cars in Alabama''s capital

Montgomery sits where I-65 meets I-85, making it a crossroads for drivers heading to Birmingham, Mobile and Atlanta. The city is home to Maxwell Air Force Base and a major automotive manufacturing presence, and its used car market reflects that mix: plenty of practical sedans and crossovers alongside pickups for work and weekend use.

### Smart shopping in Montgomery

- **Military buyers.** Service members relocating to or from Maxwell-Gunter often buy and sell on short timelines. Get pre-approved for financing before you shop so you can move quickly on the right car.
- **Compare the region.** Prattville, Millbrook and Wetumpka dealers are close by. Use a 30-mile radius to see them all in one search.
- **Highway readiness.** If you''ll drive I-85 or I-65 often, prioritize a car with good tires, a solid alignment and working cruise control. Take the test drive on the highway, not just around the lot.

### After you buy

You''ll register the vehicle with your county of residence. Montgomery County residents can use county license offices. Check current requirements and fees before you visit. Our [Alabama used car buying guide](/blog/how-to-buy-a-used-car-in-alabama) walks through the title and registration steps.', '[{"q":"Does the Montgomery search include Prattville and Wetumpka?","a":"Yes. The default search area covers dealers within about 30 miles of Montgomery, which includes Prattville, Millbrook and Wetumpka."},{"q":"I am stationed at Maxwell AFB. Can I buy a car quickly?","a":"Yes. Getting pre-approved for a loan and having your insurance information ready speeds things up. Use Request Price to get an out-the-door quote from the dealer before you visit."},{"q":"What documents do I need to register a used car in Alabama?","a":"Typically the signed title (or a bill of sale for title-exempt vehicles), proof of insurance and your ID. Requirements can change, so confirm with your county license office before visiting."},{"q":"How do I compare used car prices in Montgomery?","a":"Sort results by lowest price or use the price table on this page, which is built from live listings from Montgomery-area dealers."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('tuscaloosa-al', 'Tuscaloosa', 'Tuscaloosa County', 33.2098, -87.5692, 1, 5, 'Find used cars for sale in Tuscaloosa, AL from dealerships in Tuscaloosa and Northport. Great for students, families and commuters. Filter by price, mileage and body type, and contact dealers directly.', '## Used cars in Tuscaloosa and Northport

Tuscaloosa is home to the University of Alabama and sits on I-20/59 about an hour southwest of Birmingham. The Mercedes-Benz plant in nearby Vance makes West Alabama an automotive town, and the local used car market ranges from affordable first cars for students to late-model SUVs for families.

### Buying your first car as a student

- **Set a total budget.** Include insurance, tax, title and registration, not just the sticker price. Cars under $10,000 are popular; browse [cars under $10,000](/used-cars/under-10000) to see what''s available.
- **Prioritize reliability.** A well-maintained compact sedan with complete service records is often a smarter buy than a newer car with an unknown history.
- **Bring a second opinion.** An independent pre-purchase inspection costs far less than an unexpected repair.

### Game day and beyond

Tuscaloosa traffic on home football weekends is legendary. If you''re shopping in the fall, plan dealer visits for weekdays. You''ll get more of the salesperson''s time and an easier test drive.

### Families and commuters

For drivers commuting to Birmingham, highway comfort and fuel economy matter. Check [used SUVs in Tuscaloosa](/used-cars/tuscaloosa-al/suvs) for family-sized options.', '[{"q":"Are there cheap used cars for sale in Tuscaloosa?","a":"Yes. Use the price filter or sort by lowest price. Many Tuscaloosa and Northport dealers list vehicles under $10,000."},{"q":"I am a University of Alabama student. What should I look for in a used car?","a":"Focus on total cost of ownership: insurance, fuel and maintenance. Choose a car with service records, have it inspected, and get an out-the-door price in writing before you buy."},{"q":"Does the Tuscaloosa search include Northport?","a":"Yes. Northport dealers are included in the default Tuscaloosa radius."},{"q":"Can I get a price quote before visiting a Tuscaloosa dealer?","a":"Yes. Click Request Price on any listing and the dealer will reply with pricing details."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('hoover-al', 'Hoover', 'Jefferson and Shelby Counties', 33.4054, -86.8114, 1, 6, 'Shop used cars for sale in Hoover, AL from dealers along US-31, the I-459 corridor and across Birmingham''s southern suburbs, including Pelham, Helena and Alabaster.', '## Used cars in Hoover

Hoover is one of Alabama''s largest cities and straddles Jefferson and Shelby counties just south of Birmingham. With the Riverchase Galleria area, US-31 and I-459 nearby, it''s a convenient base for car shopping across the south metro, from Hoover itself down through Pelham, Helena and Alabaster.

### Why shop Hoover dealers

- **Suburban families.** Hoover''s market leans toward three-row SUVs, minivans and crossovers. If you need seating for seven, filter by body type and look at [SUVs in the Hoover area](/used-cars/hoover-al/suvs).
- **Two counties, one search.** Because Hoover spans two counties, your registration office depends on where you live, not where you buy. Check your county before you head out with paperwork.
- **Close to Birmingham selection.** Hoover shoppers can easily compare with Birmingham-area inventory. Just widen the radius.

### Test-drive route idea

Include a stretch of I-459 for highway manners and some of Hoover''s hillier neighborhood streets to check braking and transmission behavior under load.', '[{"q":"Is Hoover in Jefferson County or Shelby County?","a":"Hoover spans both Jefferson and Shelby counties. You register a vehicle in the county where you reside, so check which county your address is in."},{"q":"Can I find used minivans and three-row SUVs in Hoover?","a":"Yes. Filter by body type (Minivan or SUV) and use the seating details in each listing description to find family-sized vehicles."},{"q":"Does the Hoover page overlap with Birmingham?","a":"Hoover borders Birmingham, so some dealers appear in both searches. Adjust the radius or use a ZIP code to focus on the area closest to you."},{"q":"How do I contact a used car dealer in Hoover?","a":"Open a listing and use Contact Dealer. Your message goes straight to the dealership, and you will receive a confirmation email."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('auburn-al', 'Auburn', 'Lee County', 32.6099, -85.4808, 1, 7, 'Find used cars for sale in Auburn, AL from dealerships in Auburn, Opelika and across Lee County. Filter by price and mileage, compare listings and contact local dealers.', '## Used cars in Auburn and Opelika

Auburn and neighboring Opelika form one of the fastest-growing areas in East Alabama. Auburn University drives much of the demand, but a strong manufacturing base and I-85 access to Montgomery and Atlanta keep the local car market busy year-round.

### Shopping tips for Lee County

- **Student budgets.** Affordable, reliable sedans and hatchbacks move fast before fall semester. Start shopping in early summer if you can.
- **I-85 commuters.** If you''ll commute toward Montgomery or Columbus, Georgia, prioritize highway comfort and fuel economy.
- **Opelika is next door.** Many dealerships sit along the I-85 corridor in Opelika. Keep your radius at 25 miles or more to include them.

### Before you sign

Get an out-the-door price in writing, review any add-on products carefully, and confirm the title status. Our [used car buying guide](/blog/how-to-buy-a-used-car-in-alabama) covers each step.', '[{"q":"Does the Auburn search include Opelika dealers?","a":"Yes. Opelika dealers are within the default search radius for Auburn."},{"q":"When is the best time for students to buy a car in Auburn?","a":"Inventory of affordable cars tends to move quickly before the fall semester, so shopping in late spring or early summer gives you more choice."},{"q":"Can I get financing through an Auburn dealer?","a":"Many dealers offer financing. Use the Financing button on a listing to send an inquiry, and compare the dealer offer with a pre-approval from your bank or credit union."},{"q":"Are there used trucks for sale in Auburn?","a":"Yes. Filter by body type Truck, or browse used trucks across Alabama and set your location to Auburn."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('dothan-al', 'Dothan', 'Houston County', 31.2232, -85.3905, 1, 8, 'Browse used cars for sale in Dothan, AL from dealerships across the Wiregrass region: Dothan, Enterprise, Ozark and surrounding communities. Compare prices and contact dealers directly.', '## Used cars in Dothan and the Wiregrass

Dothan is the hub of Alabama''s Wiregrass region in the southeast corner of the state, near both Georgia and Florida. Known for its peanut industry, the area''s economy mixes agriculture, healthcare and the military community connected to nearby Fort Novosel. That mix shows up on dealer lots: work trucks, family SUVs and dependable commuter cars.

### What Wiregrass buyers look for

- **Trucks that work.** Rural roads and farm use mean pickups are in demand. Check bed condition, hitch wear and the service history for towing use. Browse [used trucks in Dothan](/used-cars/dothan-al/trucks).
- **Long-distance comfort.** Many Wiregrass drivers cover long distances on US-231 and US-84. Test cruise control, seat comfort and road noise.
- **Military moves.** Families relocating to or from Fort Novosel benefit from pre-approved financing and quick out-the-door quotes.

### Keep it local

Buying from a nearby dealer makes follow-up service, warranty questions and paperwork easier. Use the Dothan radius search to find sellers within driving distance.', '[{"q":"Does the Dothan search include Enterprise and Ozark?","a":"Increase the radius to 50 miles to include dealers in Enterprise, Ozark and more of the Wiregrass region."},{"q":"What should I check on a used truck in Dothan?","a":"Inspect the frame, bed and hitch for heavy-use wear, check the transmission fluid, and ask for records of towing and maintenance."},{"q":"Can military families buy cars quickly in Dothan?","a":"Yes. Get pre-approved for financing, have your insurance ready, and use Request Price for a written out-the-door quote before you visit."},{"q":"Is Dothan in Houston County?","a":"Yes, most of Dothan is in Houston County, where you would title and register a vehicle if you live there."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('decatur-al', 'Decatur', 'Morgan County', 34.6059, -86.9833, 1, 9, 'Find used cars for sale in Decatur, AL from dealers in Decatur, Hartselle, Priceville and the North Alabama river valley. Compare local listings and contact dealers directly.', '## Used cars in Decatur

Decatur sits on the Tennessee River in Morgan County, just west of Huntsville and a short drive from I-65. It''s an industrial town with a strong manufacturing base, and its car market reflects practical priorities: durable pickups, efficient commuters and family SUVs.

### Decatur shopping tips

- **Huntsville commuters.** Many Decatur residents work in Huntsville. Look for good fuel economy and comfortable highway manners for the daily drive on I-565.
- **River-town moisture.** Near the river, check for signs of water intrusion: damp carpet, musty smells and corrosion under the seats.
- **Widen the search.** Hartselle, Athens and Huntsville are nearby. A 30–50 mile radius gives you more options without a long drive.

### Pickups in Decatur

Trucks are a Decatur staple. When buying used, check the bed, tailgate, hitch receiver and transmission, and ask whether the truck has been used for regular towing.', '[{"q":"Does the Decatur page include Hartselle dealers?","a":"Yes. Dealers in Hartselle and Priceville are within the default search radius for Decatur."},{"q":"Are there used trucks for sale in Decatur, AL?","a":"Yes. Filter by body type Truck or browse used trucks in Alabama and set your location to a Decatur ZIP code."},{"q":"How far is Decatur from Huntsville dealers?","a":"Huntsville is roughly a 30-minute drive. Increase your search radius to include Huntsville and Madison inventory."},{"q":"Can I request a price from a Decatur dealer online?","a":"Yes. Click Request Price on any listing and the dealer will respond with pricing details."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('madison-al', 'Madison', 'Madison and Limestone Counties', 34.6993, -86.7483, 1, 10, 'Shop used cars for sale in Madison, AL from dealerships in Madison, Huntsville and Athens. Filter by make, price, mileage and body type, and contact local dealers directly.', '## Used cars in Madison

Madison is a fast-growing city on Huntsville''s west side, spanning Madison and Limestone counties along I-565 and US-72. Many residents work at Redstone Arsenal, Research Park or the area''s growing manufacturing employers, so reliable daily drivers and family SUVs are always in demand.

### Tips for Madison buyers

- **Family-sized choices.** Madison''s suburbs favor SUVs and minivans. Compare [used SUVs in Madison](/used-cars/madison-al/suvs) by mileage and price.
- **Check your county.** Madison spans two counties. You''ll register in the county where you live.
- **Lean on Huntsville inventory.** Huntsville dealers are minutes away; widen your radius to compare the whole metro.

### Test-drive smarter

Drive a mix of I-565 and local roads, test the infotainment and driver-assist features, and bring your phone to check Bluetooth and charging ports. Features that don''t work on the test drive rarely fix themselves.', '[{"q":"Is Madison, AL in Madison County or Limestone County?","a":"The City of Madison spans both Madison and Limestone counties. Register your vehicle in the county where you live."},{"q":"Does the Madison search include Huntsville dealers?","a":"Yes. Huntsville dealers are within the default search area around Madison."},{"q":"What used SUVs are popular in Madison?","a":"Compact and midsize crossovers and three-row SUVs are popular with Madison families. Use the SUV filter and sort by lowest mileage to compare."},{"q":"How do I save cars to compare later?","a":"Create a free account and tap the heart icon on any listing. Saved vehicles appear in your account."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('florence-al', 'Florence', 'Lauderdale County', 34.7998, -87.6773, 1, 11, 'Find used cars for sale in Florence, AL and the Shoals: Muscle Shoals, Sheffield and Tuscumbia. Compare prices and mileage from local dealers and contact them directly.', '## Used cars in Florence and the Shoals

Florence is the largest city in the Shoals, the four-city area on the Tennessee River that includes Muscle Shoals, Sheffield and Tuscumbia. Home to the University of North Alabama and a famous music heritage, the Shoals has an independent, close-knit car market where local reputation matters.

### Shoals shopping tips

- **Cross the river.** Dealers are spread across both sides of the Tennessee River. A 25-mile radius around Florence includes the whole Shoals.
- **Students and first cars.** UNA students often shop for affordable, reliable sedans. See [cars under $10,000](/used-cars/under-10000) for budget options.
- **Local reputation.** Read dealer reviews on BamaMotors and ask neighbors. In a smaller market, a dealer''s reputation is easy to check.

### Inspection reminders

Check for corrosion and moisture if a vehicle was kept near the river, confirm the title is clean, and test-drive on both town streets and US-72.', '[{"q":"Does the Florence search include Muscle Shoals?","a":"Yes. Muscle Shoals, Sheffield and Tuscumbia are all within the default Florence search radius."},{"q":"Are there affordable used cars in Florence, AL?","a":"Yes. Sort by lowest price or browse cars under $10,000 and set your location to a Florence ZIP code."},{"q":"How do I check a Shoals dealer’s reputation?","a":"Dealer pages on BamaMotors show moderated reviews from signed-in shoppers. You can also ask the dealer for references and check their license details."},{"q":"Can I schedule a test drive online?","a":"Yes. Use Schedule Test Drive on any listing and pick a preferred date."}]');
INSERT INTO cities (slug, name, county, lat, lng, is_featured, sort_order, intro, body, faq_json) VALUES ('gadsden-al', 'Gadsden', 'Etowah County', 34.0143, -86.0066, 1, 12, 'Browse used cars for sale in Gadsden, AL from dealers in Gadsden, Rainbow City, Attalla and Etowah County. Compare listings and contact local dealerships directly.', '## Used cars in Gadsden

Gadsden sits on the Coosa River in Etowah County, along I-59 between Birmingham and Chattanooga. It''s a practical market with a strong demand for trucks, SUVs and affordable daily drivers.

### Gadsden shopping tips

- **Budget-friendly options.** Gadsden often offers solid value on older, well-kept vehicles. Sort by lowest price and read each listing''s history section carefully.
- **Highway and hills.** Test-drive on I-59 and on hilly roads around Lookout Mountain''s southern end to check the transmission and brakes.
- **Compare with Birmingham.** Birmingham is about an hour away. Widen your radius if you want more options, but weigh the drive against local service convenience.

### Before you buy

Confirm the title status, request service records and get an independent inspection. Our [used car inspection checklist](/blog/how-to-inspect-a-used-car-alabama) shows what to look for.', '[{"q":"Does the Gadsden search include Rainbow City and Attalla?","a":"Yes. Rainbow City, Attalla and Southside are within the default Gadsden search radius."},{"q":"Are there used trucks for sale in Gadsden?","a":"Yes. Use the Truck body type filter or browse Gadsden trucks directly."},{"q":"What should I inspect on an older used car?","a":"Check fluid condition, tire age, rust, suspension noise, the A/C and all electronics, and ask for service records. An independent inspection is recommended."},{"q":"How do I contact a Gadsden dealer?","a":"Open any listing and use Contact Dealer or call the phone number shown on the dealer profile."}]');

-- Makes and models
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('toyota', 'Toyota', 1, 'Shop used Toyota cars, trucks and SUVs for sale in Alabama. Toyota models like the Camry, Corolla, RAV4 and Tacoma are known for long service lives and strong resale value, which makes them a favorite with Alabama shoppers who want dependable transportation.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'camry', 'Camry', 'Sedan' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'corolla', 'Corolla', 'Sedan' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'rav4', 'RAV4', 'SUV' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'tacoma', 'Tacoma', 'Truck' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'tundra', 'Tundra', 'Truck' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'highlander', 'Highlander', 'SUV' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, '4runner', '4Runner', 'SUV' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sienna', 'Sienna', 'Minivan' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'prius', 'Prius', 'Hatchback' FROM makes WHERE slug = 'toyota';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sequoia', 'Sequoia', 'SUV' FROM makes WHERE slug = 'toyota';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('honda', 'Honda', 1, 'Find used Honda cars and SUVs for sale across Alabama. The Honda Civic and Accord are long-running favorites for commuters, while the CR-V, Pilot and Odyssey cover families who need more space.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'civic', 'Civic', 'Sedan' FROM makes WHERE slug = 'honda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'accord', 'Accord', 'Sedan' FROM makes WHERE slug = 'honda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'cr-v', 'CR-V', 'SUV' FROM makes WHERE slug = 'honda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'pilot', 'Pilot', 'SUV' FROM makes WHERE slug = 'honda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'odyssey', 'Odyssey', 'Minivan' FROM makes WHERE slug = 'honda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'hr-v', 'HR-V', 'SUV' FROM makes WHERE slug = 'honda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'ridgeline', 'Ridgeline', 'Truck' FROM makes WHERE slug = 'honda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'passport', 'Passport', 'SUV' FROM makes WHERE slug = 'honda';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('ford', 'Ford', 1, 'Browse used Ford trucks, SUVs and cars for sale in Alabama. The F-150 is one of the best-selling pickups in America, and Alabama dealers also stock plenty of Explorers, Escapes, Rangers and Mustangs.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'f-150', 'F-150', 'Truck' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'f-250-super-duty', 'F-250 Super Duty', 'Truck' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'ranger', 'Ranger', 'Truck' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'mustang', 'Mustang', 'Coupe' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'explorer', 'Explorer', 'SUV' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'escape', 'Escape', 'SUV' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'expedition', 'Expedition', 'SUV' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'edge', 'Edge', 'SUV' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'bronco', 'Bronco', 'SUV' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'bronco-sport', 'Bronco Sport', 'SUV' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'maverick', 'Maverick', 'Truck' FROM makes WHERE slug = 'ford';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'fusion', 'Fusion', 'Sedan' FROM makes WHERE slug = 'ford';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('chevrolet', 'Chevrolet', 1, 'Shop used Chevrolet trucks, SUVs and cars for sale in Alabama. Chevy pickups like the Silverado and full-size SUVs like the Tahoe and Suburban are Alabama staples, alongside the Equinox, Traverse and Malibu.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'silverado-1500', 'Silverado 1500', 'Truck' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'silverado-2500hd', 'Silverado 2500HD', 'Truck' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'colorado', 'Colorado', 'Truck' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'tahoe', 'Tahoe', 'SUV' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'suburban', 'Suburban', 'SUV' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'equinox', 'Equinox', 'SUV' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'traverse', 'Traverse', 'SUV' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'trax', 'Trax', 'SUV' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'blazer', 'Blazer', 'SUV' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'malibu', 'Malibu', 'Sedan' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'camaro', 'Camaro', 'Coupe' FROM makes WHERE slug = 'chevrolet';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'corvette', 'Corvette', 'Coupe' FROM makes WHERE slug = 'chevrolet';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('gmc', 'GMC', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sierra-1500', 'Sierra 1500', 'Truck' FROM makes WHERE slug = 'gmc';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sierra-2500hd', 'Sierra 2500HD', 'Truck' FROM makes WHERE slug = 'gmc';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'canyon', 'Canyon', 'Truck' FROM makes WHERE slug = 'gmc';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'yukon', 'Yukon', 'SUV' FROM makes WHERE slug = 'gmc';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'yukon-xl', 'Yukon XL', 'SUV' FROM makes WHERE slug = 'gmc';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'acadia', 'Acadia', 'SUV' FROM makes WHERE slug = 'gmc';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'terrain', 'Terrain', 'SUV' FROM makes WHERE slug = 'gmc';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('ram', 'Ram', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, '1500', '1500', 'Truck' FROM makes WHERE slug = 'ram';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, '2500', '2500', 'Truck' FROM makes WHERE slug = 'ram';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, '3500', '3500', 'Truck' FROM makes WHERE slug = 'ram';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'promaster', 'ProMaster', 'Van' FROM makes WHERE slug = 'ram';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('nissan', 'Nissan', 1, 'Find used Nissan cars, trucks and SUVs for sale in Alabama, including the Altima, Rogue, Sentra, Frontier and Pathfinder.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'altima', 'Altima', 'Sedan' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sentra', 'Sentra', 'Sedan' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'maxima', 'Maxima', 'Sedan' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'rogue', 'Rogue', 'SUV' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'murano', 'Murano', 'SUV' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'pathfinder', 'Pathfinder', 'SUV' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'armada', 'Armada', 'SUV' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'kicks', 'Kicks', 'SUV' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'frontier', 'Frontier', 'Truck' FROM makes WHERE slug = 'nissan';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'titan', 'Titan', 'Truck' FROM makes WHERE slug = 'nissan';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('hyundai', 'Hyundai', 1, 'Shop used Hyundai cars and SUVs for sale in Alabama, including the Elantra, Sonata, Tucson, Santa Fe and Palisade.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'elantra', 'Elantra', 'Sedan' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sonata', 'Sonata', 'Sedan' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'tucson', 'Tucson', 'SUV' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'santa-fe', 'Santa Fe', 'SUV' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'palisade', 'Palisade', 'SUV' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'kona', 'Kona', 'SUV' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'venue', 'Venue', 'SUV' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'santa-cruz', 'Santa Cruz', 'Truck' FROM makes WHERE slug = 'hyundai';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'ioniq-5', 'Ioniq 5', 'SUV' FROM makes WHERE slug = 'hyundai';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('kia', 'Kia', 1, 'Browse used Kia cars and SUVs for sale in Alabama, including the Sorento, Telluride, Sportage, K5 and Forte.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'forte', 'Forte', 'Sedan' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'k5', 'K5', 'Sedan' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'optima', 'Optima', 'Sedan' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'soul', 'Soul', 'Hatchback' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sportage', 'Sportage', 'SUV' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'sorento', 'Sorento', 'SUV' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'telluride', 'Telluride', 'SUV' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'seltos', 'Seltos', 'SUV' FROM makes WHERE slug = 'kia';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'carnival', 'Carnival', 'Minivan' FROM makes WHERE slug = 'kia';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('jeep', 'Jeep', 1, 'Find used Jeep SUVs and trucks for sale in Alabama, from the Wrangler and Gladiator to the Grand Cherokee and Cherokee.');
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'wrangler', 'Wrangler', 'SUV' FROM makes WHERE slug = 'jeep';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'grand-cherokee', 'Grand Cherokee', 'SUV' FROM makes WHERE slug = 'jeep';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'cherokee', 'Cherokee', 'SUV' FROM makes WHERE slug = 'jeep';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'compass', 'Compass', 'SUV' FROM makes WHERE slug = 'jeep';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'renegade', 'Renegade', 'SUV' FROM makes WHERE slug = 'jeep';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'gladiator', 'Gladiator', 'Truck' FROM makes WHERE slug = 'jeep';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'wagoneer', 'Wagoneer', 'SUV' FROM makes WHERE slug = 'jeep';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('dodge', 'Dodge', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'charger', 'Charger', 'Sedan' FROM makes WHERE slug = 'dodge';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'challenger', 'Challenger', 'Coupe' FROM makes WHERE slug = 'dodge';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'durango', 'Durango', 'SUV' FROM makes WHERE slug = 'dodge';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'grand-caravan', 'Grand Caravan', 'Minivan' FROM makes WHERE slug = 'dodge';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('chrysler', 'Chrysler', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'pacifica', 'Pacifica', 'Minivan' FROM makes WHERE slug = 'chrysler';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, '300', '300', 'Sedan' FROM makes WHERE slug = 'chrysler';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'voyager', 'Voyager', 'Minivan' FROM makes WHERE slug = 'chrysler';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('subaru', 'Subaru', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'outback', 'Outback', 'Wagon' FROM makes WHERE slug = 'subaru';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'forester', 'Forester', 'SUV' FROM makes WHERE slug = 'subaru';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'crosstrek', 'Crosstrek', 'SUV' FROM makes WHERE slug = 'subaru';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'ascent', 'Ascent', 'SUV' FROM makes WHERE slug = 'subaru';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'impreza', 'Impreza', 'Sedan' FROM makes WHERE slug = 'subaru';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'legacy', 'Legacy', 'Sedan' FROM makes WHERE slug = 'subaru';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('mazda', 'Mazda', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'cx-5', 'CX-5', 'SUV' FROM makes WHERE slug = 'mazda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'cx-30', 'CX-30', 'SUV' FROM makes WHERE slug = 'mazda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'cx-50', 'CX-50', 'SUV' FROM makes WHERE slug = 'mazda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'cx-9', 'CX-9', 'SUV' FROM makes WHERE slug = 'mazda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'cx-90', 'CX-90', 'SUV' FROM makes WHERE slug = 'mazda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'mazda3', 'Mazda3', 'Sedan' FROM makes WHERE slug = 'mazda';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'mx-5-miata', 'MX-5 Miata', 'Convertible' FROM makes WHERE slug = 'mazda';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('volkswagen', 'Volkswagen', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'jetta', 'Jetta', 'Sedan' FROM makes WHERE slug = 'volkswagen';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'passat', 'Passat', 'Sedan' FROM makes WHERE slug = 'volkswagen';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'tiguan', 'Tiguan', 'SUV' FROM makes WHERE slug = 'volkswagen';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'atlas', 'Atlas', 'SUV' FROM makes WHERE slug = 'volkswagen';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'taos', 'Taos', 'SUV' FROM makes WHERE slug = 'volkswagen';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'golf', 'Golf', 'Hatchback' FROM makes WHERE slug = 'volkswagen';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('mercedes-benz', 'Mercedes-Benz', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'c-class', 'C-Class', 'Sedan' FROM makes WHERE slug = 'mercedes-benz';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'e-class', 'E-Class', 'Sedan' FROM makes WHERE slug = 'mercedes-benz';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'glc', 'GLC', 'SUV' FROM makes WHERE slug = 'mercedes-benz';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'gle', 'GLE', 'SUV' FROM makes WHERE slug = 'mercedes-benz';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'gls', 'GLS', 'SUV' FROM makes WHERE slug = 'mercedes-benz';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'gla', 'GLA', 'SUV' FROM makes WHERE slug = 'mercedes-benz';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('bmw', 'BMW', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, '3-series', '3 Series', 'Sedan' FROM makes WHERE slug = 'bmw';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, '5-series', '5 Series', 'Sedan' FROM makes WHERE slug = 'bmw';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'x1', 'X1', 'SUV' FROM makes WHERE slug = 'bmw';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'x3', 'X3', 'SUV' FROM makes WHERE slug = 'bmw';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'x5', 'X5', 'SUV' FROM makes WHERE slug = 'bmw';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'x7', 'X7', 'SUV' FROM makes WHERE slug = 'bmw';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('lexus', 'Lexus', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'es', 'ES', 'Sedan' FROM makes WHERE slug = 'lexus';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'is', 'IS', 'Sedan' FROM makes WHERE slug = 'lexus';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'rx', 'RX', 'SUV' FROM makes WHERE slug = 'lexus';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'nx', 'NX', 'SUV' FROM makes WHERE slug = 'lexus';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'gx', 'GX', 'SUV' FROM makes WHERE slug = 'lexus';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('acura', 'Acura', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'mdx', 'MDX', 'SUV' FROM makes WHERE slug = 'acura';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'rdx', 'RDX', 'SUV' FROM makes WHERE slug = 'acura';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'tlx', 'TLX', 'Sedan' FROM makes WHERE slug = 'acura';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'integra', 'Integra', 'Hatchback' FROM makes WHERE slug = 'acura';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('infiniti', 'Infiniti', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'qx50', 'QX50', 'SUV' FROM makes WHERE slug = 'infiniti';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'qx60', 'QX60', 'SUV' FROM makes WHERE slug = 'infiniti';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'qx80', 'QX80', 'SUV' FROM makes WHERE slug = 'infiniti';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'q50', 'Q50', 'Sedan' FROM makes WHERE slug = 'infiniti';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('audi', 'Audi', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'a4', 'A4', 'Sedan' FROM makes WHERE slug = 'audi';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'a6', 'A6', 'Sedan' FROM makes WHERE slug = 'audi';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'q3', 'Q3', 'SUV' FROM makes WHERE slug = 'audi';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'q5', 'Q5', 'SUV' FROM makes WHERE slug = 'audi';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'q7', 'Q7', 'SUV' FROM makes WHERE slug = 'audi';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('cadillac', 'Cadillac', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'escalade', 'Escalade', 'SUV' FROM makes WHERE slug = 'cadillac';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'xt4', 'XT4', 'SUV' FROM makes WHERE slug = 'cadillac';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'xt5', 'XT5', 'SUV' FROM makes WHERE slug = 'cadillac';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'xt6', 'XT6', 'SUV' FROM makes WHERE slug = 'cadillac';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'ct5', 'CT5', 'Sedan' FROM makes WHERE slug = 'cadillac';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('buick', 'Buick', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'enclave', 'Enclave', 'SUV' FROM makes WHERE slug = 'buick';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'encore', 'Encore', 'SUV' FROM makes WHERE slug = 'buick';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'encore-gx', 'Encore GX', 'SUV' FROM makes WHERE slug = 'buick';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'envision', 'Envision', 'SUV' FROM makes WHERE slug = 'buick';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('lincoln', 'Lincoln', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'navigator', 'Navigator', 'SUV' FROM makes WHERE slug = 'lincoln';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'aviator', 'Aviator', 'SUV' FROM makes WHERE slug = 'lincoln';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'nautilus', 'Nautilus', 'SUV' FROM makes WHERE slug = 'lincoln';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'corsair', 'Corsair', 'SUV' FROM makes WHERE slug = 'lincoln';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('tesla', 'Tesla', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'model-3', 'Model 3', 'Sedan' FROM makes WHERE slug = 'tesla';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'model-y', 'Model Y', 'SUV' FROM makes WHERE slug = 'tesla';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'model-s', 'Model S', 'Sedan' FROM makes WHERE slug = 'tesla';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'model-x', 'Model X', 'SUV' FROM makes WHERE slug = 'tesla';
INSERT INTO makes (slug, name, is_popular, intro) VALUES ('mitsubishi', 'Mitsubishi', 0, NULL);
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'outlander', 'Outlander', 'SUV' FROM makes WHERE slug = 'mitsubishi';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'eclipse-cross', 'Eclipse Cross', 'SUV' FROM makes WHERE slug = 'mitsubishi';
INSERT INTO models (make_id, slug, name, body_type) SELECT id, 'mirage', 'Mirage', 'Hatchback' FROM makes WHERE slug = 'mitsubishi';

-- Blog categories
INSERT INTO categories (slug, name, description, sort_order) VALUES ('car-buying-guides', 'Car Buying Guides', 'Step-by-step advice for buying a used car with confidence.', 1);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('used-car-prices', 'Used Car Prices', 'What used cars cost in Alabama, built from real listing data.', 2);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('financing', 'Financing', 'Auto loans, credit and budgeting for your next car.', 3);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('vehicle-reviews', 'Vehicle Reviews', 'Model overviews and what to look for when buying used.', 4);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('alabama-car-buying', 'Alabama Car Buying', 'Titles, registration, taxes and local advice for Alabama drivers.', 5);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('dealer-guides', 'Dealer Guides', 'Resources for Alabama dealerships listing on BamaMotors.', 6);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('maintenance', 'Maintenance', 'Keep your car running well in Alabama heat, humidity and storms.', 7);

-- 839 Alabama ZIP codes for radius search
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('35004', 'Moody', 'AL', 33.6035, -86.4668),
  ('35005', 'Adamsville', 'AL', 33.5884, -86.9597),
  ('35006', 'Adger', 'AL', 33.4343, -87.1675),
  ('35007', 'Alabaster', 'AL', 33.1934, -86.7944),
  ('35010', 'Alexander City', 'AL', 32.9164, -85.9368),
  ('35011', 'Alexander City', 'AL', 32.9902, -85.958),
  ('35013', 'Allgood', 'AL', 33.9222, -86.4493),
  ('35014', 'Alpine', 'AL', 33.404, -86.2339),
  ('35015', 'Alton', 'AL', 33.5793, -86.6375),
  ('35016', 'Arab', 'AL', 34.3283, -86.4896),
  ('35019', 'Baileyton', 'AL', 34.2683, -86.6213),
  ('35020', 'Bessemer', 'AL', 33.409, -86.9475),
  ('35021', 'Bessemer', 'AL', 33.5446, -86.9292),
  ('35022', 'Bessemer', 'AL', 33.3224, -86.9657),
  ('35023', 'Bessemer', 'AL', 33.468, -87.0924),
  ('35031', 'Blountsville', 'AL', 34.0929, -86.5686),
  ('35032', 'Bon Air', 'AL', 33.2649, -86.3364),
  ('35033', 'Bremen', 'AL', 33.9737, -87.0043),
  ('35034', 'Brent', 'AL', 32.9357, -87.2114),
  ('35035', 'Brierfield', 'AL', 33.0427, -86.9517),
  ('35036', 'Brookside', 'AL', 33.6379, -86.9167),
  ('35038', 'Burnwell', 'AL', 33.7079, -87.0875),
  ('35040', 'Calera', 'AL', 33.1098, -86.756),
  ('35041', 'Cardiff', 'AL', 33.64, -86.92),
  ('35042', 'Centreville', 'AL', 32.9503, -87.1192),
  ('35043', 'Chelsea', 'AL', 33.2982, -86.6563),
  ('35044', 'Childersburg', 'AL', 33.2459, -86.3641),
  ('35045', 'Clanton', 'AL', 32.8355, -86.6425),
  ('35046', 'Clanton', 'AL', 32.9229, -86.545),
  ('35048', 'Clay', 'AL', 33.7026, -86.5997),
  ('35049', 'Cleveland', 'AL', 33.9778, -86.5598),
  ('35051', 'Columbiana', 'AL', 33.177, -86.6161),
  ('35052', 'Cook Springs', 'AL', 33.5895, -86.3923),
  ('35053', 'Crane Hill', 'AL', 34.0821, -87.0484),
  ('35054', 'Cropwell', 'AL', 33.5296, -86.3007),
  ('35055', 'Cullman', 'AL', 34.1761, -86.8298),
  ('35056', 'Cullman', 'AL', 34.1748, -86.8436),
  ('35057', 'Cullman', 'AL', 34.0878, -86.9447),
  ('35058', 'Cullman', 'AL', 34.2098, -86.752),
  ('35060', 'Docena', 'AL', 33.5589, -86.9294),
  ('35061', 'Dolomite', 'AL', 33.4654, -86.9564),
  ('35062', 'Dora', 'AL', 33.7357, -87.0546),
  ('35063', 'Empire', 'AL', 33.8256, -87.0161),
  ('35064', 'Fairfield', 'AL', 33.4735, -86.9183),
  ('35068', 'Fultondale', 'AL', 33.6017, -86.8265),
  ('35070', 'Garden City', 'AL', 34.0058, -86.7499),
  ('35071', 'Gardendale', 'AL', 33.7189, -86.8225),
  ('35072', 'Goodwater', 'AL', 33.0746, -86.0781),
  ('35073', 'Graysville', 'AL', 33.6539, -86.9803),
  ('35074', 'Green Pond', 'AL', 33.2251, -87.1264),
  ('35077', 'Hanceville', 'AL', 34.0516, -86.7848),
  ('35078', 'Harpersville', 'AL', 33.3234, -86.4424),
  ('35079', 'Hayden', 'AL', 33.9534, -86.7455),
  ('35080', 'Helena', 'AL', 33.2663, -86.902),
  ('35082', 'Hollins', 'AL', 33.1162, -86.1386),
  ('35083', 'Holly Pond', 'AL', 34.1901, -86.6174),
  ('35085', 'Jemison', 'AL', 32.9805, -86.7181),
  ('35087', 'Joppa', 'AL', 34.2837, -86.5519),
  ('35089', 'Kellyton', 'AL', 32.9791, -86.0484),
  ('35091', 'Kimberly', 'AL', 33.7684, -86.8084),
  ('35094', 'Leeds', 'AL', 33.5283, -86.5748),
  ('35096', 'Lincoln', 'AL', 33.6059, -86.1112),
  ('35097', 'Locust Fork', 'AL', 33.905, -86.6261),
  ('35098', 'Logan', 'AL', 34.1377, -87.0266),
  ('35111', 'Mc Calla', 'AL', 33.2845, -87.1024),
  ('35112', 'Margaret', 'AL', 33.6862, -86.475),
  ('35114', 'Maylene', 'AL', 33.2317, -86.8727),
  ('35115', 'Montevallo', 'AL', 33.1248, -86.8622),
  ('35116', 'Morris', 'AL', 33.7392, -86.7726),
  ('35117', 'Mount Olive', 'AL', 33.6768, -86.8717),
  ('35118', 'Mulga', 'AL', 33.5363, -87.051),
  ('35119', 'New Castle', 'AL', 33.649, -86.7686),
  ('35120', 'Odenville', 'AL', 33.6756, -86.409),
  ('35121', 'Oneonta', 'AL', 33.9259, -86.4741),
  ('35123', 'Palmerdale', 'AL', 33.7387, -86.6461),
  ('35124', 'Pelham', 'AL', 33.2932, -86.768),
  ('35125', 'Pell City', 'AL', 33.5979, -86.3432),
  ('35126', 'Pinson', 'AL', 33.7299, -86.6451),
  ('35127', 'Pleasant Grove', 'AL', 33.4883, -86.9766),
  ('35128', 'Pell City', 'AL', 33.5873, -86.3366),
  ('35130', 'Quinton', 'AL', 33.6561, -87.1007),
  ('35131', 'Ragland', 'AL', 33.7367, -86.1619),
  ('35133', 'Remlap', 'AL', 33.8168, -86.6008),
  ('35135', 'Riverside', 'AL', 33.6166, -86.1996),
  ('35136', 'Rockford', 'AL', 32.878, -86.24),
  ('35137', 'Saginaw', 'AL', 33.2063, -86.7812),
  ('35139', 'Sayre', 'AL', 33.7111, -86.9759),
  ('35142', 'Shannon', 'AL', 33.4069, -86.8735),
  ('35143', 'Shelby', 'AL', 33.0785, -86.5536),
  ('35144', 'Siluria', 'AL', 33.2293, -86.825),
  ('35146', 'Springville', 'AL', 33.7386, -86.4394),
  ('35147', 'Sterrett', 'AL', 33.4461, -86.4917),
  ('35148', 'Sumiton', 'AL', 33.768, -87.0445),
  ('35149', 'Sycamore', 'AL', 33.2512, -86.2025),
  ('35150', 'Sylacauga', 'AL', 33.1717, -86.2713),
  ('35151', 'Sylacauga', 'AL', 33.1756, -86.3574),
  ('35160', 'Talladega', 'AL', 33.4354, -86.1134),
  ('35161', 'Talladega', 'AL', 33.4202, -86.1028),
  ('35171', 'Thorsby', 'AL', 32.9157, -86.7158),
  ('35172', 'Trafford', 'AL', 33.819, -86.7434);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('35173', 'Trussville', 'AL', 33.6339, -86.5981),
  ('35175', 'Union Grove', 'AL', 34.4093, -86.4628),
  ('35176', 'Vandiver', 'AL', 33.4807, -86.5013),
  ('35178', 'Vincent', 'AL', 33.401, -86.3994),
  ('35179', 'Vinemont', 'AL', 34.2621, -86.9125),
  ('35180', 'Warrior', 'AL', 33.8529, -86.8198),
  ('35181', 'Watson', 'AL', 33.5446, -86.9292),
  ('35182', 'Wattsville', 'AL', 33.7068, -86.2567),
  ('35183', 'Weogufka', 'AL', 33.0238, -86.3042),
  ('35184', 'West Blocton', 'AL', 33.1424, -87.1369),
  ('35185', 'Westover', 'AL', 33.3356, -86.5437),
  ('35186', 'Wilsonville', 'AL', 33.2293, -86.5299),
  ('35187', 'Wilton', 'AL', 33.081, -86.8793),
  ('35188', 'Woodstock', 'AL', 33.2068, -87.15),
  ('35201', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35202', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35203', 'Birmingham', 'AL', 33.521, -86.8066),
  ('35204', 'Birmingham', 'AL', 33.5179, -86.8372),
  ('35205', 'Birmingham', 'AL', 33.4951, -86.8059),
  ('35206', 'Birmingham', 'AL', 33.5678, -86.7199),
  ('35207', 'Birmingham', 'AL', 33.5594, -86.8153),
  ('35208', 'Birmingham', 'AL', 33.4977, -86.8799),
  ('35209', 'Birmingham', 'AL', 33.4653, -86.8082),
  ('35210', 'Birmingham', 'AL', 33.5452, -86.6655),
  ('35211', 'Birmingham', 'AL', 33.4816, -86.859),
  ('35212', 'Birmingham', 'AL', 33.5409, -86.7495),
  ('35213', 'Birmingham', 'AL', 33.5066, -86.7428),
  ('35214', 'Birmingham', 'AL', 33.5554, -86.887),
  ('35215', 'Birmingham', 'AL', 33.6493, -86.7057),
  ('35216', 'Birmingham', 'AL', 33.4188, -86.7867),
  ('35217', 'Birmingham', 'AL', 33.5887, -86.765),
  ('35218', 'Birmingham', 'AL', 33.506, -86.893),
  ('35219', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35220', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35221', 'Birmingham', 'AL', 33.4523, -86.8935),
  ('35222', 'Birmingham', 'AL', 33.5219, -86.7666),
  ('35223', 'Birmingham', 'AL', 33.4995, -86.7268),
  ('35224', 'Birmingham', 'AL', 33.5191, -86.9342),
  ('35225', 'Bham', 'AL', 33.46, -86.81),
  ('35226', 'Birmingham', 'AL', 33.3967, -86.8346),
  ('35228', 'Birmingham', 'AL', 33.4558, -86.9118),
  ('35229', 'Birmingham', 'AL', 33.4629, -86.7904),
  ('35230', 'Bham', 'AL', 33.46, -86.81),
  ('35231', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35232', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35233', 'Birmingham', 'AL', 33.5062, -86.8003),
  ('35234', 'Birmingham', 'AL', 33.5378, -86.8068),
  ('35235', 'Birmingham', 'AL', 33.6328, -86.6493),
  ('35236', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35237', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35238', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35240', 'Bham', 'AL', 33.46, -86.81),
  ('35242', 'Birmingham', 'AL', 33.3813, -86.7046),
  ('35243', 'Birmingham', 'AL', 33.4459, -86.7502),
  ('35244', 'Birmingham', 'AL', 33.3538, -86.8254),
  ('35245', 'Bham', 'AL', 33.46, -86.81),
  ('35246', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35249', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35253', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35254', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35255', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35259', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35260', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35261', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35263', 'Bham', 'AL', 33.53, -86.78),
  ('35266', 'Birmingham', 'AL', 33.3729, -86.8531),
  ('35270', 'Birmingham', 'AL', 33.5206, -86.8025),
  ('35277', 'Bham', 'AL', 33.44, -86.73),
  ('35278', 'Oxmoor House', 'AL', 33.46, -86.81),
  ('35279', 'Parisians Inc', 'AL', 33.42, -86.78),
  ('35280', 'Bham', 'AL', 33.51, -86.8),
  ('35281', 'Decorative Craft Ideas', 'AL', 33.51, -86.8),
  ('35282', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35283', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35285', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35286', 'Bham', 'AL', 33.42, -86.78),
  ('35287', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35288', 'Birmingham', 'AL', 33.4458, -86.9285),
  ('35289', 'Assc Doctors Ins', 'AL', 33.51, -86.8),
  ('35290', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35291', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35292', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35293', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35294', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35295', 'Birmingham', 'AL', 33.5207, -86.8025),
  ('35296', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35297', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35298', 'Birmingham', 'AL', 33.5446, -86.9292),
  ('35299', 'Birmingham', 'AL', 33.51, -86.8),
  ('35401', 'Tuscaloosa', 'AL', 33.1969, -87.5627),
  ('35402', 'Tuscaloosa', 'AL', 33.3066, -87.4532),
  ('35403', 'Tuscaloosa', 'AL', 33.2045, -87.527),
  ('35404', 'Tuscaloosa', 'AL', 33.1826, -87.4827),
  ('35405', 'Tuscaloosa', 'AL', 33.1617, -87.5144),
  ('35406', 'Tuscaloosa', 'AL', 33.2722, -87.536),
  ('35407', 'Tuscaloosa', 'AL', 33.3066, -87.4532),
  ('35440', 'Abernant', 'AL', 33.311, -87.1898),
  ('35441', 'Akron', 'AL', 32.8553, -87.7219),
  ('35442', 'Aliceville', 'AL', 33.1228, -88.1667),
  ('35443', 'Boligee', 'AL', 32.7746, -88.0267);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('35444', 'Brookwood', 'AL', 33.2775, -87.309),
  ('35446', 'Buhl', 'AL', 33.2306, -87.7547),
  ('35447', 'Carrollton', 'AL', 33.2485, -88.1321),
  ('35448', 'Clinton', 'AL', 32.9137, -87.9925),
  ('35449', 'Coaling', 'AL', 33.1359, -87.3384),
  ('35452', 'Coker', 'AL', 33.2934, -87.6888),
  ('35453', 'Cottondale', 'AL', 33.1767, -87.3871),
  ('35456', 'Duncanville', 'AL', 33.0618, -87.4422),
  ('35457', 'Echola', 'AL', 33.294, -87.7766),
  ('35458', 'Elrod', 'AL', 33.2562, -87.7922),
  ('35459', 'Emelle', 'AL', 32.755, -88.3057),
  ('35460', 'Epes', 'AL', 32.672, -88.1206),
  ('35461', 'Ethelsville', 'AL', 33.4157, -88.2167),
  ('35462', 'Eutaw', 'AL', 32.8889, -87.9303),
  ('35463', 'Fosters', 'AL', 33.0843, -87.6975),
  ('35464', 'Gainesville', 'AL', 32.821, -88.1589),
  ('35466', 'Gordo', 'AL', 33.3469, -87.9005),
  ('35468', 'Kellerman', 'AL', 33.3407, -87.3047),
  ('35469', 'Knoxville', 'AL', 32.9824, -87.7919),
  ('35470', 'Livingston', 'AL', 32.5843, -88.1872),
  ('35471', 'Mc Shan', 'AL', 33.2626, -88.0885),
  ('35473', 'Northport', 'AL', 33.2723, -87.5825),
  ('35474', 'Moundville', 'AL', 32.9108, -87.5935),
  ('35475', 'Northport', 'AL', 33.3992, -87.5599),
  ('35476', 'Northport', 'AL', 33.2273, -87.5943),
  ('35477', 'Panola', 'AL', 32.8726, -88.2374),
  ('35478', 'Peterson', 'AL', 33.3066, -87.4532),
  ('35480', 'Ralph', 'AL', 33.1274, -87.7624),
  ('35481', 'Reform', 'AL', 33.3959, -88.0203),
  ('35482', 'Samantha', 'AL', 33.3066, -87.4532),
  ('35485', 'Tuscaloosa', 'AL', 33.23, -87.54),
  ('35486', 'Tuscaloosa', 'AL', 33.2098, -87.5692),
  ('35487', 'Tuscaloosa', 'AL', 33.3072, -87.5859),
  ('35490', 'Vance', 'AL', 33.175, -87.2574),
  ('35491', 'West Greene', 'AL', 32.9237, -88.0853),
  ('35501', 'Jasper', 'AL', 33.8312, -87.2775),
  ('35502', 'Jasper', 'AL', 33.8312, -87.2775),
  ('35503', 'Jasper', 'AL', 33.9152, -87.3074),
  ('35504', 'Jasper', 'AL', 33.8927, -87.1667),
  ('35540', 'Addison', 'AL', 34.2056, -87.1948),
  ('35541', 'Arley', 'AL', 34.0632, -87.1828),
  ('35542', 'Bankston', 'AL', 33.7008, -87.6897),
  ('35543', 'Bear Creek', 'AL', 34.1649, -87.7396),
  ('35544', 'Beaverton', 'AL', 33.9429, -88.0157),
  ('35545', 'Belk', 'AL', 33.6476, -87.9314),
  ('35546', 'Berry', 'AL', 33.6945, -87.6226),
  ('35548', 'Brilliant', 'AL', 34.0377, -87.7563),
  ('35549', 'Carbon Hill', 'AL', 33.9093, -87.5403),
  ('35550', 'Cordova', 'AL', 33.768, -87.1841),
  ('35551', 'Delmar', 'AL', 34.1701, -87.6059),
  ('35552', 'Detroit', 'AL', 34.0282, -88.17),
  ('35553', 'Double Springs', 'AL', 34.1387, -87.3974),
  ('35554', 'Eldridge', 'AL', 33.9315, -87.6194),
  ('35555', 'Fayette', 'AL', 33.6974, -87.8346),
  ('35559', 'Glen Allen', 'AL', 33.9151, -87.7417),
  ('35560', 'Goodsprings', 'AL', 33.6795, -87.2374),
  ('35563', 'Guin', 'AL', 33.9676, -87.9024),
  ('35564', 'Hackleburg', 'AL', 34.2678, -87.8608),
  ('35565', 'Haleyville', 'AL', 34.2314, -87.5938),
  ('35570', 'Hamilton', 'AL', 34.1534, -88.0085),
  ('35571', 'Hodges', 'AL', 34.3417, -87.959),
  ('35572', 'Houston', 'AL', 34.118, -87.2618),
  ('35573', 'Kansas', 'AL', 33.9018, -87.552),
  ('35574', 'Kennedy', 'AL', 33.6153, -87.9948),
  ('35575', 'Lynn', 'AL', 34.053, -87.5398),
  ('35576', 'Millport', 'AL', 33.5401, -88.2),
  ('35577', 'Natural Bridge', 'AL', 34.0934, -87.6008),
  ('35578', 'Nauvoo', 'AL', 33.9299, -87.4324),
  ('35579', 'Oakman', 'AL', 33.7002, -87.3686),
  ('35580', 'Parrish', 'AL', 33.7213, -87.2658),
  ('35581', 'Phil Campbell', 'AL', 34.347, -87.7154),
  ('35582', 'Red Bay', 'AL', 34.4513, -88.1129),
  ('35584', 'Sipsey', 'AL', 33.8201, -87.0779),
  ('35585', 'Spruce Pine', 'AL', 34.4246, -87.8145),
  ('35586', 'Sulligent', 'AL', 33.8549, -88.1508),
  ('35587', 'Townley', 'AL', 33.847, -87.4372),
  ('35592', 'Vernon', 'AL', 33.7613, -88.0979),
  ('35593', 'Vina', 'AL', 34.3712, -88.0774),
  ('35594', 'Winfield', 'AL', 33.9303, -87.7972),
  ('35601', 'Decatur', 'AL', 34.5896, -86.9887),
  ('35602', 'Decatur', 'AL', 34.6059, -86.9833),
  ('35603', 'Decatur', 'AL', 34.5484, -87.0004),
  ('35609', 'Decatur', 'AL', 34.6059, -86.9833),
  ('35610', 'Anderson', 'AL', 34.9424, -87.2734),
  ('35611', 'Athens', 'AL', 34.8036, -86.9707),
  ('35612', 'Athens', 'AL', 34.7749, -87.0305),
  ('35613', 'Athens', 'AL', 34.8317, -86.8867),
  ('35614', 'Athens', 'AL', 34.8474, -87.0607),
  ('35615', 'Belle Mina', 'AL', 34.6568, -86.8792),
  ('35616', 'Cherokee', 'AL', 34.7442, -87.9724),
  ('35617', 'Cloverdale', 'AL', 34.9387, -87.7714),
  ('35618', 'Courtland', 'AL', 34.6719, -87.3143),
  ('35619', 'Danville', 'AL', 34.3873, -87.1454),
  ('35620', 'Elkmont', 'AL', 34.929, -86.9739),
  ('35621', 'Eva', 'AL', 34.3323, -86.7589),
  ('35622', 'Falkville', 'AL', 34.3477, -86.9131),
  ('35630', 'Florence', 'AL', 34.8305, -87.656),
  ('35631', 'Florence', 'AL', 34.87, -87.7069),
  ('35632', 'Florence', 'AL', 34.87, -87.7069),
  ('35633', 'Florence', 'AL', 34.8825, -87.7398);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('35634', 'Florence', 'AL', 34.9186, -87.6136),
  ('35640', 'Hartselle', 'AL', 34.4482, -86.9242),
  ('35643', 'Hillsboro', 'AL', 34.6476, -87.1804),
  ('35645', 'Killen', 'AL', 34.9016, -87.5082),
  ('35646', 'Leighton', 'AL', 34.711, -87.5221),
  ('35647', 'Lester', 'AL', 34.9596, -87.1006),
  ('35648', 'Lexington', 'AL', 34.9559, -87.3935),
  ('35649', 'Mooresville', 'AL', 34.6259, -86.8746),
  ('35650', 'Moulton', 'AL', 34.5058, -87.2224),
  ('35651', 'Mount Hope', 'AL', 34.4793, -87.4769),
  ('35652', 'Rogersville', 'AL', 34.8495, -87.3237),
  ('35653', 'Russellville', 'AL', 34.5066, -87.7257),
  ('35654', 'Russellville', 'AL', 34.4675, -87.6478),
  ('35660', 'Sheffield', 'AL', 34.7578, -87.6971),
  ('35661', 'Muscle Shoals', 'AL', 34.7561, -87.6304),
  ('35662', 'Muscle Shoals', 'AL', 34.7448, -87.6675),
  ('35670', 'Somerville', 'AL', 34.4995, -86.8009),
  ('35671', 'Tanner', 'AL', 34.6796, -86.9625),
  ('35672', 'Town Creek', 'AL', 34.6491, -87.4262),
  ('35673', 'Trinity', 'AL', 34.5918, -87.0913),
  ('35674', 'Tuscumbia', 'AL', 34.6874, -87.6833),
  ('35677', 'Waterloo', 'AL', 34.9357, -87.9624),
  ('35699', 'Decatur', 'AL', 34.6059, -86.9833),
  ('35739', 'Ardmore', 'AL', 34.9804, -86.8346),
  ('35740', 'Bridgeport', 'AL', 34.9446, -85.7277),
  ('35741', 'Brownsboro', 'AL', 34.7167, -86.4687),
  ('35742', 'Capshaw', 'AL', 34.7731, -86.7928),
  ('35744', 'Dutton', 'AL', 34.6046, -85.9067),
  ('35745', 'Estillfork', 'AL', 34.913, -86.1716),
  ('35746', 'Fackler', 'AL', 34.8259, -85.9846),
  ('35747', 'Grant', 'AL', 34.4959, -86.259),
  ('35748', 'Gurley', 'AL', 34.714, -86.394),
  ('35749', 'Harvest', 'AL', 34.8273, -86.7499),
  ('35750', 'Hazel Green', 'AL', 34.9496, -86.5935),
  ('35751', 'Hollytree', 'AL', 34.7955, -86.2743),
  ('35752', 'Hollywood', 'AL', 34.7304, -85.9532),
  ('35754', 'Laceys Spring', 'AL', 34.4996, -86.6129),
  ('35755', 'Langston', 'AL', 34.5001, -86.1353),
  ('35756', 'Madison', 'AL', 34.643, -86.8168),
  ('35757', 'Madison', 'AL', 34.7782, -86.7442),
  ('35758', 'Madison', 'AL', 34.7108, -86.7425),
  ('35759', 'Meridianville', 'AL', 34.8618, -86.5789),
  ('35760', 'New Hope', 'AL', 34.5494, -86.3961),
  ('35761', 'New Market', 'AL', 34.9, -86.4487),
  ('35762', 'Normal', 'AL', 34.789, -86.5719),
  ('35763', 'Owens Cross Roads', 'AL', 34.6215, -86.4644),
  ('35764', 'Paint Rock', 'AL', 34.7031, -86.3068),
  ('35765', 'Pisgah', 'AL', 34.6809, -85.8478),
  ('35766', 'Princeton', 'AL', 34.8713, -86.2513),
  ('35767', 'Ryland', 'AL', 34.7698, -86.4808),
  ('35768', 'Scottsboro', 'AL', 34.7507, -86.1422),
  ('35769', 'Scottsboro', 'AL', 34.618, -86.0562),
  ('35771', 'Section', 'AL', 34.5433, -85.994),
  ('35772', 'Stevenson', 'AL', 34.8769, -85.8508),
  ('35773', 'Toney', 'AL', 34.9116, -86.7),
  ('35774', 'Trenton', 'AL', 34.7632, -86.2295),
  ('35775', 'Valhermoso Springs', 'AL', 34.542, -86.6871),
  ('35776', 'Woodville', 'AL', 34.6689, -86.2296),
  ('35801', 'Huntsville', 'AL', 34.7269, -86.5673),
  ('35802', 'Huntsville', 'AL', 34.6679, -86.5603),
  ('35803', 'Huntsville', 'AL', 34.6205, -86.551),
  ('35804', 'Huntsville', 'AL', 34.7284, -86.5853),
  ('35805', 'Huntsville', 'AL', 34.7059, -86.6165),
  ('35806', 'Huntsville', 'AL', 34.7448, -86.6704),
  ('35807', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35808', 'Huntsville', 'AL', 34.6845, -86.6538),
  ('35809', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35810', 'Huntsville', 'AL', 34.7784, -86.6091),
  ('35811', 'Huntsville', 'AL', 34.7789, -86.5438),
  ('35812', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35813', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35814', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35815', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35816', 'Huntsville', 'AL', 34.7389, -86.6249),
  ('35824', 'Huntsville', 'AL', 34.6583, -86.7295),
  ('35893', 'Huntsville', 'AL', 34.7304, -86.5861),
  ('35894', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35895', 'Huntsville', 'AL', 34.7304, -86.5861),
  ('35896', 'Huntsville', 'AL', 34.7543, -86.6546),
  ('35897', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35898', 'Huntsville', 'AL', 34.734, -86.5229),
  ('35899', 'Huntsville', 'AL', 34.7339, -86.6456),
  ('35901', 'Gadsden', 'AL', 34.048, -85.9246),
  ('35902', 'Gadsden', 'AL', 34.0143, -86.0066),
  ('35903', 'Gadsden', 'AL', 33.9845, -85.9077),
  ('35904', 'Gadsden', 'AL', 34.0217, -86.0495),
  ('35905', 'Gadsden', 'AL', 33.9352, -85.9576),
  ('35906', 'Rainbow City', 'AL', 33.9318, -86.0898),
  ('35907', 'Gadsden', 'AL', 33.8979, -86.0245),
  ('35950', 'Albertville', 'AL', 34.2739, -86.2064),
  ('35951', 'Albertville', 'AL', 34.3223, -86.1935),
  ('35952', 'Altoona', 'AL', 34.071, -86.2096),
  ('35953', 'Ashville', 'AL', 33.8374, -86.2552),
  ('35954', 'Attalla', 'AL', 34.0296, -86.0967),
  ('35956', 'Boaz', 'AL', 34.1437, -86.148),
  ('35957', 'Boaz', 'AL', 34.1921, -86.1941),
  ('35958', 'Bryant', 'AL', 34.945, -85.6324),
  ('35959', 'Cedar Bluff', 'AL', 34.2417, -85.6026),
  ('35960', 'Centre', 'AL', 34.1116, -85.6092),
  ('35961', 'Collinsville', 'AL', 34.268, -85.862);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('35962', 'Crossville', 'AL', 34.2588, -86.0306),
  ('35963', 'Dawson', 'AL', 34.3568, -85.9292),
  ('35964', 'Douglas', 'AL', 34.1737, -86.3236),
  ('35966', 'Flat Rock', 'AL', 34.8076, -85.7084),
  ('35967', 'Fort Payne', 'AL', 34.4368, -85.7124),
  ('35968', 'Fort Payne', 'AL', 34.4898, -85.7657),
  ('35971', 'Fyffe', 'AL', 34.4373, -85.9288),
  ('35972', 'Gallant', 'AL', 33.9976, -86.2346),
  ('35973', 'Gaylesville', 'AL', 34.3573, -85.5589),
  ('35974', 'Geraldine', 'AL', 34.3592, -86.024),
  ('35975', 'Groveoak', 'AL', 34.4359, -86.04),
  ('35976', 'Guntersville', 'AL', 34.3449, -86.2752),
  ('35978', 'Henagar', 'AL', 34.6186, -85.7274),
  ('35979', 'Higdon', 'AL', 34.8391, -85.6196),
  ('35980', 'Horton', 'AL', 34.19, -86.3173),
  ('35981', 'Ider', 'AL', 34.7351, -85.6416),
  ('35983', 'Leesburg', 'AL', 34.1911, -85.7705),
  ('35984', 'Mentone', 'AL', 34.5872, -85.5777),
  ('35986', 'Rainsville', 'AL', 34.4989, -85.8446),
  ('35987', 'Steele', 'AL', 33.9417, -86.2289),
  ('35988', 'Sylvania', 'AL', 34.559, -85.7921),
  ('35989', 'Valley Head', 'AL', 34.5697, -85.6272),
  ('35990', 'Walnut Grove', 'AL', 34.0657, -86.3064),
  ('36003', 'Autaugaville', 'AL', 32.4625, -86.7149),
  ('36005', 'Banks', 'AL', 31.8368, -85.7998),
  ('36006', 'Billingsley', 'AL', 32.6596, -86.7178),
  ('36008', 'Booth', 'AL', 32.5016, -86.5727),
  ('36009', 'Brantley', 'AL', 31.571, -86.2743),
  ('36010', 'Brundidge', 'AL', 31.7013, -85.8177),
  ('36013', 'Cecil', 'AL', 32.2937, -85.9827),
  ('36015', 'Chapman', 'AL', 31.6427, -86.7343),
  ('36016', 'Clayton', 'AL', 31.8874, -85.4509),
  ('36017', 'Clio', 'AL', 31.6852, -85.5904),
  ('36020', 'Coosada', 'AL', 32.5056, -86.3322),
  ('36022', 'Deatsville', 'AL', 32.6082, -86.3958),
  ('36023', 'East Tallassee', 'AL', 32.8002, -85.8034),
  ('36024', 'Eclectic', 'AL', 32.6542, -86.0316),
  ('36025', 'Elmore', 'AL', 32.5454, -86.3161),
  ('36026', 'Equality', 'AL', 32.8139, -86.1051),
  ('36027', 'Eufaula', 'AL', 31.9051, -85.1656),
  ('36028', 'Dozier', 'AL', 31.5066, -86.3663),
  ('36029', 'Fitzpatrick', 'AL', 32.2165, -85.8888),
  ('36030', 'Forest Home', 'AL', 31.8501, -86.8372),
  ('36031', 'Fort Davis', 'AL', 32.2507, -85.7524),
  ('36032', 'Fort Deposit', 'AL', 31.996, -86.5761),
  ('36033', 'Georgiana', 'AL', 31.6287, -86.734),
  ('36034', 'Glenwood', 'AL', 31.6641, -86.171),
  ('36035', 'Goshen', 'AL', 31.7946, -86.1277),
  ('36036', 'Grady', 'AL', 32.0194, -86.1292),
  ('36037', 'Greenville', 'AL', 31.81, -86.6229),
  ('36038', 'Gantt', 'AL', 31.4068, -86.4841),
  ('36039', 'Hardaway', 'AL', 32.3129, -85.8838),
  ('36040', 'Hayneville', 'AL', 32.1957, -86.655),
  ('36041', 'Highland Home', 'AL', 31.9283, -86.2971),
  ('36042', 'Honoraville', 'AL', 31.8784, -86.3981),
  ('36043', 'Hope Hull', 'AL', 32.2243, -86.3932),
  ('36045', 'Kent', 'AL', 32.619, -85.9486),
  ('36046', 'Lapine', 'AL', 31.9657, -86.2844),
  ('36047', 'Letohatchee', 'AL', 32.0862, -86.488),
  ('36048', 'Louisville', 'AL', 31.7943, -85.5581),
  ('36049', 'Luverne', 'AL', 31.7074, -86.2566),
  ('36051', 'Marbury', 'AL', 32.6841, -86.4946),
  ('36052', 'Mathews', 'AL', 32.1283, -86.0413),
  ('36053', 'Midway', 'AL', 32.0955, -85.5315),
  ('36054', 'Millbrook', 'AL', 32.4995, -86.3641),
  ('36057', 'Mount Meigs', 'AL', 32.2334, -86.2085),
  ('36061', 'Perote', 'AL', 32.0928, -85.7046),
  ('36062', 'Petrey', 'AL', 31.8488, -86.2077),
  ('36064', 'Pike Road', 'AL', 32.3357, -86.0959),
  ('36065', 'Pine Level', 'AL', 32.0726, -86.0606),
  ('36066', 'Prattville', 'AL', 32.4787, -86.43),
  ('36067', 'Prattville', 'AL', 32.4715, -86.4831),
  ('36068', 'Prattville', 'AL', 32.464, -86.4597),
  ('36069', 'Ramer', 'AL', 32.0677, -86.2463),
  ('36071', 'Rutledge', 'AL', 31.7062, -86.3715),
  ('36072', 'Eufaula', 'AL', 31.8913, -85.1455),
  ('36075', 'Shorter', 'AL', 32.3836, -85.9162),
  ('36078', 'Tallassee', 'AL', 32.551, -85.8978),
  ('36079', 'Troy', 'AL', 31.7595, -86.0107),
  ('36080', 'Titus', 'AL', 32.69, -86.2393),
  ('36081', 'Troy', 'AL', 31.7945, -85.9655),
  ('36082', 'Troy', 'AL', 31.8028, -85.9546),
  ('36083', 'Tuskegee', 'AL', 32.4316, -85.6861),
  ('36087', 'Tuskegee Institute', 'AL', 32.4093, -85.738),
  ('36088', 'Tuskegee Institute', 'AL', 32.4145, -85.7253),
  ('36089', 'Union Springs', 'AL', 32.1443, -85.7149),
  ('36091', 'Verbena', 'AL', 32.7499, -86.5114),
  ('36092', 'Wetumpka', 'AL', 32.5927, -86.2153),
  ('36093', 'Wetumpka', 'AL', 32.5622, -86.0994),
  ('36101', 'Montgomery', 'AL', 32.357, -86.2578),
  ('36102', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36103', 'Montgomery', 'AL', 32.3462, -86.2873),
  ('36104', 'Montgomery', 'AL', 32.373, -86.3081),
  ('36105', 'Montgomery', 'AL', 32.3257, -86.3104),
  ('36106', 'Montgomery', 'AL', 32.3543, -86.2673),
  ('36107', 'Montgomery', 'AL', 32.3804, -86.2799),
  ('36108', 'Montgomery', 'AL', 32.3417, -86.3529),
  ('36109', 'Montgomery', 'AL', 32.3834, -86.2434),
  ('36110', 'Montgomery', 'AL', 32.4217, -86.275),
  ('36111', 'Montgomery', 'AL', 32.3374, -86.2715);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('36112', 'Montgomery', 'AL', 32.3808, -86.3491),
  ('36113', 'Montgomery', 'AL', 32.3846, -86.3039),
  ('36114', 'Montgomery', 'AL', 32.404, -86.2539),
  ('36115', 'Montgomery', 'AL', 32.4076, -86.2474),
  ('36116', 'Montgomery', 'AL', 32.3129, -86.2421),
  ('36117', 'Montgomery', 'AL', 32.3736, -86.1833),
  ('36118', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36119', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36120', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36121', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36123', 'Montgomery', 'AL', 32.3668, -86.3),
  ('36124', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36125', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36130', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36131', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36132', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36133', 'Montgomery', 'AL', 32.35, -86.28),
  ('36134', 'Montgomery', 'AL', 32.35, -86.28),
  ('36135', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36140', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36141', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36142', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36177', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36191', 'Montgomery', 'AL', 32.2334, -86.2085),
  ('36201', 'Anniston', 'AL', 33.6539, -85.8382),
  ('36202', 'Anniston', 'AL', 33.7622, -85.8378),
  ('36203', 'Oxford', 'AL', 33.5815, -85.8328),
  ('36204', 'Anniston', 'AL', 33.7622, -85.8378),
  ('36205', 'Anniston', 'AL', 33.7358, -85.7933),
  ('36206', 'Anniston', 'AL', 33.7191, -85.8389),
  ('36207', 'Anniston', 'AL', 33.6803, -85.7137),
  ('36210', 'Anniston', 'AL', 33.65, -85.77),
  ('36250', 'Alexandria', 'AL', 33.7808, -85.8924),
  ('36251', 'Ashland', 'AL', 33.2474, -85.829),
  ('36253', 'Bynum', 'AL', 33.7622, -85.8378),
  ('36254', 'Choccolocco', 'AL', 33.6573, -85.6991),
  ('36255', 'Cragford', 'AL', 33.2171, -85.7108),
  ('36256', 'Daviston', 'AL', 33.0335, -85.7538),
  ('36257', 'De Armanville', 'AL', 33.7622, -85.8378),
  ('36258', 'Delta', 'AL', 33.4573, -85.6793),
  ('36260', 'Eastaboga', 'AL', 33.6031, -85.9608),
  ('36261', 'Edwardsville', 'AL', 33.7066, -85.5099),
  ('36262', 'Fruithurst', 'AL', 33.7717, -85.4381),
  ('36263', 'Graham', 'AL', 33.463, -85.334),
  ('36264', 'Heflin', 'AL', 33.6115, -85.5885),
  ('36265', 'Jacksonville', 'AL', 33.831, -85.7752),
  ('36266', 'Lineville', 'AL', 33.3286, -85.7346),
  ('36267', 'Millerville', 'AL', 33.1915, -85.9258),
  ('36268', 'Munford', 'AL', 33.541, -85.9363),
  ('36269', 'Muscadine', 'AL', 33.7529, -85.3789),
  ('36271', 'Ohatchee', 'AL', 33.7788, -86.0254),
  ('36272', 'Piedmont', 'AL', 33.8389, -85.646),
  ('36273', 'Ranburne', 'AL', 33.5616, -85.3786),
  ('36274', 'Roanoke', 'AL', 33.1512, -85.3722),
  ('36275', 'Spring Garden', 'AL', 33.9778, -85.5521),
  ('36276', 'Wadley', 'AL', 33.1492, -85.5513),
  ('36277', 'Weaver', 'AL', 33.7563, -85.8107),
  ('36278', 'Wedowee', 'AL', 33.3019, -85.4737),
  ('36279', 'Wellington', 'AL', 33.8226, -85.8927),
  ('36280', 'Woodland', 'AL', 33.3743, -85.3997),
  ('36301', 'Dothan', 'AL', 31.1481, -85.3718),
  ('36302', 'Dothan', 'AL', 31.2232, -85.3905),
  ('36303', 'Dothan', 'AL', 31.2668, -85.3971),
  ('36304', 'Dothan', 'AL', 31.156, -85.3559),
  ('36305', 'Dothan', 'AL', 31.2197, -85.4828),
  ('36310', 'Abbeville', 'AL', 31.5755, -85.279),
  ('36311', 'Ariton', 'AL', 31.583, -85.7077),
  ('36312', 'Ashford', 'AL', 31.1888, -85.2535),
  ('36313', 'Bellwood', 'AL', 31.1732, -85.7933),
  ('36314', 'Black', 'AL', 31.0132, -85.7456),
  ('36316', 'Chancellor', 'AL', 31.1767, -85.8135),
  ('36317', 'Clopton', 'AL', 31.6446, -85.3911),
  ('36318', 'Coffee Springs', 'AL', 31.1388, -85.9182),
  ('36319', 'Columbia', 'AL', 31.3352, -85.1455),
  ('36320', 'Cottonwood', 'AL', 31.0507, -85.3154),
  ('36321', 'Cowarts', 'AL', 31.2025, -85.3014),
  ('36322', 'Daleville', 'AL', 31.2811, -85.7305),
  ('36323', 'Elba', 'AL', 31.4137, -86.0777),
  ('36330', 'Enterprise', 'AL', 31.3408, -85.8421),
  ('36331', 'Enterprise', 'AL', 31.2978, -85.9036),
  ('36340', 'Geneva', 'AL', 31.0414, -85.8847),
  ('36343', 'Gordon', 'AL', 31.1002, -85.1234),
  ('36344', 'Hartford', 'AL', 31.086, -85.7192),
  ('36345', 'Headland', 'AL', 31.3534, -85.3323),
  ('36346', 'Jack', 'AL', 31.5652, -85.971),
  ('36349', 'Malvern', 'AL', 31.1212, -85.5592),
  ('36350', 'Midland City', 'AL', 31.3191, -85.4938),
  ('36351', 'New Brockton', 'AL', 31.369, -85.9404),
  ('36352', 'Newton', 'AL', 31.3311, -85.5992),
  ('36353', 'Newville', 'AL', 31.4403, -85.3287),
  ('36360', 'Ozark', 'AL', 31.4391, -85.6436),
  ('36361', 'Ozark', 'AL', 31.4591, -85.6405),
  ('36362', 'Fort Rucker', 'AL', 31.348, -85.7214),
  ('36370', 'Pansey', 'AL', 31.1403, -85.1573),
  ('36371', 'Pinckard', 'AL', 31.3074, -85.5263),
  ('36373', 'Shorterville', 'AL', 31.501, -85.1135),
  ('36374', 'Skipperville', 'AL', 31.5748, -85.537),
  ('36375', 'Slocomb', 'AL', 31.0956, -85.583),
  ('36376', 'Webb', 'AL', 31.2656, -85.2544),
  ('36401', 'Evergreen', 'AL', 31.458, -86.9258);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('36420', 'Andalusia', 'AL', 31.2971, -86.4905),
  ('36421', 'Andalusia', 'AL', 31.3247, -86.5067),
  ('36425', 'Beatrice', 'AL', 31.7273, -87.1719),
  ('36426', 'Brewton', 'AL', 31.1294, -87.0961),
  ('36427', 'Brewton', 'AL', 31.1052, -87.0722),
  ('36429', 'Brooklyn', 'AL', 31.2627, -86.7711),
  ('36432', 'Castleberry', 'AL', 31.2991, -87.0225),
  ('36435', 'Coy', 'AL', 31.8889, -87.3926),
  ('36436', 'Dickinson', 'AL', 31.7635, -87.7106),
  ('36439', 'Excel', 'AL', 31.4279, -87.3414),
  ('36441', 'Flomaton', 'AL', 31.0402, -87.2664),
  ('36442', 'Florala', 'AL', 31.0172, -86.3385),
  ('36444', 'Franklin', 'AL', 31.7238, -87.4412),
  ('36445', 'Frisco City', 'AL', 31.4235, -87.3817),
  ('36446', 'Fulton', 'AL', 31.7925, -87.72),
  ('36449', 'Goodway', 'AL', 31.3368, -87.4258),
  ('36451', 'Grove Hill', 'AL', 31.7088, -87.7772),
  ('36453', 'Kinston', 'AL', 31.1926, -86.1514),
  ('36454', 'Lenox', 'AL', 31.3366, -87.1855),
  ('36455', 'Lockhart', 'AL', 31.0105, -86.3497),
  ('36456', 'Mc Kenzie', 'AL', 31.545, -86.7356),
  ('36457', 'Megargel', 'AL', 31.3612, -87.4353),
  ('36458', 'Mexia', 'AL', 31.5147, -87.4084),
  ('36460', 'Monroeville', 'AL', 31.5153, -87.341),
  ('36461', 'Monroeville', 'AL', 31.5221, -87.3411),
  ('36462', 'Monroeville', 'AL', 31.51, -87.32),
  ('36467', 'Opp', 'AL', 31.2799, -86.2571),
  ('36470', 'Perdue Hill', 'AL', 31.5141, -87.4933),
  ('36471', 'Peterman', 'AL', 31.59, -87.26),
  ('36473', 'Range', 'AL', 31.3058, -87.2137),
  ('36474', 'Red Level', 'AL', 31.4399, -86.6121),
  ('36475', 'Repton', 'AL', 31.4256, -87.172),
  ('36476', 'River Falls', 'AL', 31.3533, -86.541),
  ('36477', 'Samson', 'AL', 31.1049, -86.0674),
  ('36480', 'Uriah', 'AL', 31.3135, -87.5705),
  ('36481', 'Vredenburgh', 'AL', 31.8085, -87.3164),
  ('36482', 'Whatley', 'AL', 31.6395, -87.6565),
  ('36483', 'Wing', 'AL', 31.0223, -86.6293),
  ('36501', 'Alma', 'AL', 31.46, -87.73),
  ('36502', 'Atmore', 'AL', 31.0572, -87.4873),
  ('36503', 'Atmore', 'AL', 31.0238, -87.4939),
  ('36504', 'Atmore', 'AL', 31.0158, -87.4972),
  ('36505', 'Axis', 'AL', 30.9394, -88.0159),
  ('36507', 'Bay Minette', 'AL', 30.8635, -87.7644),
  ('36509', 'Bayou La Batre', 'AL', 30.408, -88.2507),
  ('36511', 'Bon Secour', 'AL', 30.3128, -87.7431),
  ('36512', 'Bucks', 'AL', 31.0105, -88.0242),
  ('36513', 'Calvert', 'AL', 31.1552, -88.01),
  ('36515', 'Carlton', 'AL', 31.34, -87.84),
  ('36518', 'Chatom', 'AL', 31.4876, -88.2699),
  ('36521', 'Chunchula', 'AL', 30.9912, -88.1311),
  ('36522', 'Citronelle', 'AL', 31.0425, -88.2549),
  ('36523', 'Coden', 'AL', 30.3903, -88.2076),
  ('36524', 'Coffeeville', 'AL', 31.7843, -88.0715),
  ('36525', 'Creola', 'AL', 30.9013, -88.0174),
  ('36526', 'Daphne', 'AL', 30.6197, -87.8895),
  ('36527', 'Spanish Fort', 'AL', 30.6959, -87.8867),
  ('36528', 'Dauphin Island', 'AL', 30.2521, -88.1096),
  ('36529', 'Deer Park', 'AL', 31.2168, -88.3172),
  ('36530', 'Elberta', 'AL', 30.3942, -87.589),
  ('36532', 'Fairhope', 'AL', 30.5012, -87.8835),
  ('36533', 'Fairhope', 'AL', 30.4841, -87.8606),
  ('36535', 'Foley', 'AL', 30.4007, -87.6857),
  ('36536', 'Foley', 'AL', 30.4222, -87.7064),
  ('36538', 'Frankville', 'AL', 31.6468, -88.1332),
  ('36539', 'Fruitdale', 'AL', 31.3488, -88.3766),
  ('36540', 'Gainestown', 'AL', 31.4258, -87.6822),
  ('36541', 'Grand Bay', 'AL', 30.4983, -88.3282),
  ('36542', 'Gulf Shores', 'AL', 30.2717, -87.7589),
  ('36543', 'Huxford', 'AL', 31.2202, -87.4619),
  ('36544', 'Irvington', 'AL', 30.4802, -88.2396),
  ('36545', 'Jackson', 'AL', 31.5131, -87.8672),
  ('36547', 'Gulf Shores', 'AL', 30.246, -87.7008),
  ('36548', 'Leroy', 'AL', 31.491, -87.9687),
  ('36549', 'Lillian', 'AL', 30.3972, -87.4745),
  ('36550', 'Little River', 'AL', 31.2246, -87.7548),
  ('36551', 'Loxley', 'AL', 30.618, -87.7562),
  ('36553', 'Mc Intosh', 'AL', 31.2361, -88.0511),
  ('36555', 'Magnolia Springs', 'AL', 30.3996, -87.7761),
  ('36556', 'Malcolm', 'AL', 31.1913, -88.0075),
  ('36558', 'Millry', 'AL', 31.6269, -88.3559),
  ('36559', 'Montrose', 'AL', 30.5623, -87.9005),
  ('36560', 'Mount Vernon', 'AL', 31.0974, -88.035),
  ('36561', 'Orange Beach', 'AL', 30.281, -87.5815),
  ('36562', 'Perdido', 'AL', 31.0403, -87.6667),
  ('36564', 'Point Clear', 'AL', 30.4741, -87.9192),
  ('36567', 'Robertsdale', 'AL', 30.5616, -87.6373),
  ('36568', 'Saint Elmo', 'AL', 30.5035, -88.2542),
  ('36569', 'Saint Stephens', 'AL', 31.533, -88.0521),
  ('36571', 'Saraland', 'AL', 30.8332, -88.0934),
  ('36572', 'Satsuma', 'AL', 30.8516, -88.0533),
  ('36574', 'Seminole', 'AL', 30.5048, -87.4659),
  ('36575', 'Semmes', 'AL', 30.7544, -88.2667),
  ('36576', 'Silverhill', 'AL', 30.5222, -87.7457),
  ('36577', 'Spanish Fort', 'AL', 30.6749, -87.9153),
  ('36578', 'Stapleton', 'AL', 30.7476, -87.7787),
  ('36579', 'Stockton', 'AL', 31.0129, -87.8633),
  ('36580', 'Summerdale', 'AL', 30.4752, -87.6992),
  ('36581', 'Sunflower', 'AL', 31.3696, -88.0122),
  ('36582', 'Theodore', 'AL', 30.5444, -88.1807);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('36583', 'Tibbie', 'AL', 31.4067, -88.1758),
  ('36584', 'Vinegar Bend', 'AL', 31.2584, -88.3865),
  ('36585', 'Wagarville', 'AL', 31.4102, -88.0705),
  ('36587', 'Wilmer', 'AL', 30.8137, -88.3332),
  ('36590', 'Theodore', 'AL', 30.488, -88.2533),
  ('36601', 'Mobile', 'AL', 30.6944, -88.0431),
  ('36602', 'Mobile', 'AL', 30.6888, -88.0453),
  ('36603', 'Mobile', 'AL', 30.6921, -88.0562),
  ('36604', 'Mobile', 'AL', 30.682, -88.0678),
  ('36605', 'Mobile', 'AL', 30.6341, -88.0846),
  ('36606', 'Mobile', 'AL', 30.6729, -88.1009),
  ('36607', 'Mobile', 'AL', 30.6975, -88.1029),
  ('36608', 'Mobile', 'AL', 30.6817, -88.2945),
  ('36609', 'Mobile', 'AL', 30.6605, -88.1618),
  ('36610', 'Mobile', 'AL', 30.7309, -88.0789),
  ('36611', 'Mobile', 'AL', 30.7705, -88.0781),
  ('36612', 'Mobile', 'AL', 30.7518, -88.1131),
  ('36613', 'Eight Mile', 'AL', 30.7951, -88.1823),
  ('36615', 'Mobile', 'AL', 30.6411, -88.0622),
  ('36616', 'Mobile', 'AL', 30.671, -88.1267),
  ('36617', 'Mobile', 'AL', 30.7145, -88.0918),
  ('36618', 'Mobile', 'AL', 30.7322, -88.1758),
  ('36619', 'Mobile', 'AL', 30.5928, -88.1946),
  ('36621', 'First National Bank', 'AL', 30.69, -88.04),
  ('36622', 'Merchants National Bank', 'AL', 30.69, -88.04),
  ('36625', 'Mobile', 'AL', 30.68, -88.04),
  ('36628', 'Mobile', 'AL', 30.6944, -88.0431),
  ('36630', 'Mobile', 'AL', 30.68, -88.04),
  ('36633', 'Mobile', 'AL', 30.6589, -88.178),
  ('36640', 'Mobile', 'AL', 30.6589, -88.178),
  ('36641', 'Mobile', 'AL', 30.6589, -88.178),
  ('36644', 'Mobile', 'AL', 30.6944, -88.0431),
  ('36652', 'Mobile', 'AL', 30.6944, -88.0431),
  ('36660', 'Mobile', 'AL', 30.6589, -88.178),
  ('36663', 'Mobile', 'AL', 30.6944, -88.0431),
  ('36670', 'Mobile', 'AL', 30.6589, -88.178),
  ('36671', 'Mobile', 'AL', 30.6589, -88.178),
  ('36675', 'Mobile', 'AL', 30.6944, -88.0431),
  ('36685', 'Mobile', 'AL', 30.6589, -88.178),
  ('36688', 'Mobile', 'AL', 30.6962, -88.1821),
  ('36689', 'Mobile', 'AL', 30.6589, -88.178),
  ('36690', 'Firms', 'AL', 30.69, -88.04),
  ('36691', 'Mobile', 'AL', 30.6944, -88.0431),
  ('36693', 'Mobile', 'AL', 30.6311, -88.1588),
  ('36695', 'Mobile', 'AL', 30.6474, -88.2292),
  ('36701', 'Selma', 'AL', 32.4197, -87.0245),
  ('36702', 'Selma', 'AL', 32.4074, -87.0211),
  ('36703', 'Selma', 'AL', 32.4156, -87.0135),
  ('36720', 'Alberta', 'AL', 32.1585, -87.3468),
  ('36721', 'Annemanie', 'AL', 32.07, -87.56),
  ('36722', 'Arlington', 'AL', 32.0668, -87.5597),
  ('36723', 'Boykin', 'AL', 32.0779, -87.2814),
  ('36726', 'Camden', 'AL', 32.0047, -87.295),
  ('36727', 'Campbell', 'AL', 31.9213, -88.008),
  ('36728', 'Catherine', 'AL', 32.182, -87.4836),
  ('36732', 'Demopolis', 'AL', 32.4908, -87.8397),
  ('36736', 'Dixons Mills', 'AL', 32.0672, -87.7454),
  ('36738', 'Faunsdale', 'AL', 32.4233, -87.6181),
  ('36740', 'Forkland', 'AL', 32.6108, -87.8441),
  ('36741', 'Furman', 'AL', 32.0061, -86.9817),
  ('36742', 'Gallion', 'AL', 32.5298, -87.6985),
  ('36744', 'Greensboro', 'AL', 32.7167, -87.5905),
  ('36745', 'Jefferson', 'AL', 32.414, -87.8986),
  ('36748', 'Linden', 'AL', 32.3053, -87.7954),
  ('36749', 'Jones', 'AL', 32.5104, -86.8138),
  ('36750', 'Maplesville', 'AL', 32.8045, -86.8717),
  ('36751', 'Lower Peach Tree', 'AL', 31.8504, -87.5682),
  ('36752', 'Lowndesboro', 'AL', 32.2943, -86.6471),
  ('36753', 'Mc Williams', 'AL', 32.0481, -87.2623),
  ('36754', 'Magnolia', 'AL', 32.1419, -87.6998),
  ('36756', 'Marion', 'AL', 32.6463, -87.3314),
  ('36758', 'Plantersville', 'AL', 32.6176, -86.9475),
  ('36759', 'Marion Junction', 'AL', 32.4266, -87.2702),
  ('36761', 'Minter', 'AL', 32.1899, -87.0633),
  ('36762', 'Morvin', 'AL', 31.98, -87.99),
  ('36763', 'Myrtlewood', 'AL', 32.2516, -87.9494),
  ('36764', 'Nanafalia', 'AL', 32.1129, -87.9881),
  ('36765', 'Newbern', 'AL', 32.5515, -87.5615),
  ('36766', 'Oak Hill', 'AL', 31.947, -87.0745),
  ('36767', 'Orrville', 'AL', 32.2949, -87.2214),
  ('36768', 'Pine Apple', 'AL', 31.9265, -87.0047),
  ('36769', 'Pine Hill', 'AL', 31.9735, -87.5771),
  ('36773', 'Safford', 'AL', 32.3002, -87.3693),
  ('36775', 'Sardis', 'AL', 32.2844, -86.992),
  ('36776', 'Sawyerville', 'AL', 32.7578, -87.7402),
  ('36782', 'Sweet Water', 'AL', 32.0773, -87.9228),
  ('36783', 'Thomaston', 'AL', 32.2538, -87.5974),
  ('36784', 'Thomasville', 'AL', 31.9067, -87.7598),
  ('36785', 'Tyler', 'AL', 32.3239, -86.8646),
  ('36786', 'Uniontown', 'AL', 32.447, -87.4934),
  ('36790', 'Stanton', 'AL', 32.7332, -86.8963),
  ('36792', 'Randolph', 'AL', 32.8888, -86.907),
  ('36793', 'Lawley', 'AL', 32.8646, -86.9567),
  ('36801', 'Opelika', 'AL', 32.6454, -85.3783),
  ('36802', 'Opelika', 'AL', 32.5782, -85.349),
  ('36803', 'Opelika', 'AL', 32.6454, -85.3783),
  ('36804', 'Opelika', 'AL', 32.5768, -85.312),
  ('36830', 'Auburn', 'AL', 32.5475, -85.4682),
  ('36831', 'Auburn', 'AL', 32.6099, -85.4808),
  ('36832', 'Auburn', 'AL', 32.592, -85.5189);
INSERT INTO zip_codes (zip, city, state, lat, lng) VALUES ('36849', 'Auburn University', 'AL', 32.6024, -85.4873),
  ('36850', 'Camp Hill', 'AL', 32.7827, -85.6474),
  ('36851', 'Cottonton', 'AL', 32.1468, -85.0738),
  ('36852', 'Cusseta', 'AL', 32.7831, -85.2756),
  ('36853', 'Dadeville', 'AL', 32.8224, -85.7704),
  ('36854', 'Valley', 'AL', 32.8113, -85.1749),
  ('36855', 'Five Points', 'AL', 33.0424, -85.3243),
  ('36856', 'Fort Mitchell', 'AL', 32.2965, -84.9972),
  ('36858', 'Hatchechubbee', 'AL', 32.2845, -85.3029),
  ('36859', 'Holy Trinity', 'AL', 32.2298, -85.0082),
  ('36860', 'Hurtsboro', 'AL', 32.2454, -85.3959),
  ('36861', 'Jacksons Gap', 'AL', 32.8797, -85.8487),
  ('36862', 'Lafayette', 'AL', 32.9252, -85.4426),
  ('36863', 'Lanett', 'AL', 32.8616, -85.2161),
  ('36865', 'Loachapoka', 'AL', 32.6043, -85.5933),
  ('36866', 'Notasulga', 'AL', 32.5437, -85.6871),
  ('36867', 'Phenix City', 'AL', 32.4978, -85.0234),
  ('36868', 'Phenix City', 'AL', 32.4646, -85.0206),
  ('36869', 'Phenix City', 'AL', 32.4204, -85.0796),
  ('36870', 'Phenix City', 'AL', 32.4781, -85.124),
  ('36871', 'Pittsview', 'AL', 32.1733, -85.1312),
  ('36872', 'Valley', 'AL', 32.5782, -85.349),
  ('36874', 'Salem', 'AL', 32.6212, -85.184),
  ('36875', 'Seale', 'AL', 32.3053, -85.1677),
  ('36877', 'Smiths Station', 'AL', 32.5401, -85.0985),
  ('36879', 'Waverly', 'AL', 32.7632, -85.5144),
  ('36901', 'Bellamy', 'AL', 32.449, -88.1336),
  ('36904', 'Butler', 'AL', 32.0829, -88.2064),
  ('36907', 'Cuba', 'AL', 32.411, -88.3611),
  ('36908', 'Gilbertown', 'AL', 31.8666, -88.3265),
  ('36910', 'Jachin', 'AL', 32.2299, -88.1684),
  ('36912', 'Lisman', 'AL', 32.2177, -88.3234),
  ('36913', 'Melvin', 'AL', 31.9304, -88.4589),
  ('36915', 'Needham', 'AL', 31.9879, -88.3367),
  ('36916', 'Pennington', 'AL', 32.2094, -88.049),
  ('36919', 'Silas', 'AL', 31.7668, -88.3091),
  ('36921', 'Toxey', 'AL', 31.9155, -88.151),
  ('36922', 'Ward', 'AL', 32.3038, -88.1476),
  ('36925', 'York', 'AL', 32.4728, -88.2683);

-- Editorial byline account (cannot sign in: password hash is not a valid PBKDF2 string)
INSERT INTO users (email, password_hash, name, role, status, author_slug, author_title, author_bio) VALUES ('editorial@bamamotors.com', '!disabled', 'BamaMotors Editorial Team', 'admin', 'active', 'bamamotors-editorial-team', 'Editorial Team', 'The BamaMotors editorial team writes and maintains our car buying, financing and ownership guides for Alabama drivers. We research title, registration, tax and consumer-protection topics from official sources such as the Alabama Department of Revenue, the FTC and NHTSA, cite those sources in our articles, and review guides regularly so they stay current. Dealers cannot pay for editorial coverage.');
